/// Run Solo analysis engine.
///
/// Pure Dart: no Flutter, no platform channels, no I/O. The only place verdict
/// logic lives (plan §2 rule 1).
library;

export 'src/engine/analysis.dart';
export 'src/engine/best_efforts.dart';
export 'src/engine/coach_report.dart';
export 'src/engine/coaching_rules.dart';
export 'src/engine/constants.dart';
export 'src/engine/cooper_projection.dart';
export 'src/engine/cooper_result.dart';
export 'src/engine/elevation.dart';
export 'src/engine/event_names.dart';
export 'src/engine/parkrun_courses.dart';
export 'src/engine/plans.dart';
export 'src/engine/run_identity.dart';
export 'src/engine/run_zone.dart';
export 'src/engine/run_times.dart';
export 'src/engine/fitness_hero.dart';
export 'src/engine/fix_laps.dart';
export 'src/engine/format.dart';
export 'src/engine/goal.dart';
export 'src/engine/hr_zone.dart';
export 'src/engine/identity_scores.dart';
export 'src/engine/friend_fitness_norms.dart';
export 'src/engine/leaderboards.dart';
export 'src/engine/live_card.dart';
export 'src/engine/live_plan.dart';
export 'src/engine/live_figures.dart';
export 'src/engine/max_hr.dart';
export 'src/engine/metrics.dart';
export 'src/engine/predictor.dart';
export 'src/engine/start_target.dart';
export 'src/engine/rep_detector.dart';
export 'src/engine/trace.dart';
export 'src/engine/route_match.dart';
export 'src/engine/trail_run.dart';
export 'src/engine/spoken_verdict.dart';
export 'src/engine/true_pace.dart';
export 'src/engine/run_true_pace.dart';
export 'src/engine/trail_verdict.dart';
export 'src/engine/verdict_builder.dart';
export 'src/engine_version.dart';
export 'src/import/gpx_exporter.dart';
export 'src/import/gpx_importer.dart';
export 'src/import/import_dedupe.dart';
export 'src/import/import_util.dart';
export 'src/import/run_bundle.dart';
export 'src/import/tcx_exporter.dart';
export 'src/import/tcx_importer.dart';
export 'src/model/run_file.dart';
export 'src/model/session_catalogue.dart';
export 'src/model/session_spec.dart';
export 'src/model/sidecar.dart';
export 'src/model/verdict.dart';
export 'src/route/saved_route.dart';
export 'src/run_mode.dart';
export 'src/weather/cooper_heat.dart';
export 'src/weather/heat_model.dart';
export 'src/weather/weather.dart';
export 'src/engine/percentile_curve.dart';
export 'src/engine/race_percentile_norms.dart';
