// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Run type picked at Start (plan §18.2, Phase 3 §3.8). Mirrors `RunMode` in
/// `package:run_engine`.
///
/// - `intervals`: the phases follow a `SessionSpec` (cues, auto-laps, manual LAP
///   overrides). Schema <= 2 `fourByFour` files map here.
/// - `laps`: by-feel laps; LAP button, notification LAP and volume keys (opt-in,
///   default on). Schema-1 `free` files map here (plan §18.7). A fartlek is
///   `laps` with the steps-empty fartlek spec.
/// - `free`: no lap input at all — no LAP button, no notification LAP action, no
///   MediaSession; `lap()` is a no-op (`FaultKind.lapIgnored` in debug builds).
/// - `cooper`: the 12-minute test with the Cooper spec: no LAP, `startReps`
///   starts the 12:00, projection cues. Not offered in the UI yet.
enum RecordMode {
  intervals,
  laps,
  free,
  cooper,
}

enum Units {
  km,
  mi,
}

enum RecorderState {
  idle,
  recording,
  paused,
  finalising,
}

/// Phase of an intervals run; `none` in the other modes.
enum Phase {
  none,
  warmup,
  work,
  recovery,
  cooldown,
}

enum LapSource {
  button,
  notification,
  volumeKey,
  auto,
}

/// `distanceToGo`, `lastRep`, `minuteMark`, `countdown` and `projection` are
/// Phase 3 cues (I2); I1 never emits them.
enum CueKind {
  halfway,
  thirtySeconds,
  phaseEnd,
  start,
  stop,
  distanceToGo,
  lastRep,
  minuteMark,
  countdown,
  projection,
}

enum StepKind {
  work,
  recovery,
}

/// `time`: value in seconds; `distance`: metres; `equalToPreviousWork`: value
/// 0, lasts as long as the work step before it took (Yasso, pyramids).
enum TargetKind {
  time,
  distance,
  equalToPreviousWork,
}

/// Work steps are always `run`; recoveries `jog`, `walk` or `stand`.
enum RecoveryStyle {
  run,
  jog,
  walk,
  stand,
}

enum CueProfile {
  standard,
  short,
  cooper,
}

enum FaultKind {
  gpsLost,
  gpsWeak,
  hrDisconnected,
  journalWriteFailed,
  lowStorage,
  /// The OS killed the process mid-run (read from ApplicationExitInfo on the
  /// next app open); the UI shows the OEM guidance from `exitDiagnosis`.
  osKilledMidRun,
  /// The foreground service could not start after `start` returned a run id;
  /// the run was discarded (no file). Show the message, return to Start.
  startFailed,
  /// A LAP arrived in `free` (or `cooper`) mode and was ignored. Debug builds
  /// only; a UI that shows a LAP control in that mode has a bug.
  lapIgnored,
  /// Android 14 only: volume keys never reach an app's session there, so
  /// volume-key laps are off. Fired at most once per run when volume-key laps
  /// are on; show a one-time note "use the lock-screen LAP".
  volumeKeyUnavailable,
}

/// Typed errors returned by `start` (plan §2). Never a stringly-typed map.
enum StartError {
  noFinePermission,
  approximateOnly,
  locationOff,
  lowStorage,
  notificationsDenied,
  alreadyRunning,
  /// `startReplay` on a release build, or an unknown fixture name.
  replayUnavailable,
  /// `resumeRecovered` for a journal that no longer exists or is unreadable.
  noSuchJournal,
  /// The OS refused the location foreground service (Android 14+ background
  /// start, or the permission was revoked between check and start). Nothing
  /// was recorded; no run file is written.
  fgsNotAllowed,
  /// A brand-new run failed before recording began (storage, journal open);
  /// its empty journal was discarded. Try again.
  startFailed,
  /// `resumeRecovered` failed while reopening the journal. The journal is
  /// untouched and `recover()` will list it again.
  resumeFailed,
  /// The session fails validation or does not fit the mode (intervals and
  /// cooper need their session, laps takes only the fartlek, free none).
  /// Nothing started.
  unsupportedSession,
}

/// Runtime permissions the setup checklist can request (plan §10). Location is
/// the system prompt only (never a deep link); bluetooth = SCAN + CONNECT on
/// API 31+, nothing to request below.
enum PermissionKind {
  location,
  notifications,
  bluetooth,
}

/// Why the previous process died, from `ApplicationExitInfo` (API 30+).
enum ExitReason {
  /// No kill recorded for this run (normal stop, or API 29).
  none,
  osKilled,
  lowMemory,
  crash,
  userStop,
  other,
}

/// Which kind of board a run races live (Phase 4 §3.2).
enum LiveBoardKind {
  distance,
  intervals,
  cooper,
}

/// One expanded step (named `SessionStep`: a generated `Step` would clash
/// with Flutter material's `Step`). `repIndex` is 1-based; a recovery carries
/// the rep number of the work step before it (run-file JSON key `rep`).
class SessionStep {
  SessionStep({
    required this.kind,
    required this.target,
    required this.value,
    required this.style,
    required this.repIndex,
  });

  StepKind kind;

  TargetKind target;

  int value;

  RecoveryStyle style;

  int repIndex;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      target,
      value,
      style,
      repIndex,
    ];
  }

  Object encode() {
    return _toList();  }

  static SessionStep decode(Object result) {
    result as List<Object?>;
    return SessionStep(
      kind: result[0]! as StepKind,
      target: result[1]! as TargetKind,
      value: result[2]! as int,
      style: result[3]! as RecoveryStyle,
      repIndex: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionStep || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(target, other.target) && _deepEquals(value, other.value) && _deepEquals(style, other.style) && _deepEquals(repIndex, other.repIndex);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// The expanded session (Phase 3 §3.3): Dart expands presets and custom
/// templates, Kotlin validates, journals and runs the flat step list. Written
/// to the run file as `session` (hrBand as `[low, high]`).
class SessionSpec {
  SessionSpec({
    required this.templateId,
    required this.templateVersion,
    required this.name,
    this.warmupSeconds,
    this.cooldownSeconds,
    required this.lapLockout,
    this.autoStop,
    required this.cueProfile,
    this.hrBandLow,
    this.hrBandHigh,
    required this.steps,
  });

  String templateId;

  int templateVersion;

  String name;

  /// null = open (ends on the first LAP / `startReps`); 0 = none, step 1
  /// starts at `start()` (parkrun); otherwise fixed seconds (300..1200).
  int? warmupSeconds;

  /// null = open (runs until Stop); int = fixed seconds.
  int? cooldownSeconds;

  bool lapLockout;

  /// The recording stops itself when the last timed part ends (the last step,
  /// or a fixed cool-down): parkrun stops at 5.00 km. Null = false.
  bool? autoStop;

  CueProfile cueProfile;

  double? hrBandLow;

  double? hrBandHigh;

  List<SessionStep> steps;

  List<Object?> _toList() {
    return <Object?>[
      templateId,
      templateVersion,
      name,
      warmupSeconds,
      cooldownSeconds,
      lapLockout,
      autoStop,
      cueProfile,
      hrBandLow,
      hrBandHigh,
      steps,
    ];
  }

  Object encode() {
    return _toList();  }

  static SessionSpec decode(Object result) {
    result as List<Object?>;
    return SessionSpec(
      templateId: result[0]! as String,
      templateVersion: result[1]! as int,
      name: result[2]! as String,
      warmupSeconds: result[3] as int?,
      cooldownSeconds: result[4] as int?,
      lapLockout: result[5]! as bool,
      autoStop: result[6] as bool?,
      cueProfile: result[7]! as CueProfile,
      hrBandLow: result[8] as double?,
      hrBandHigh: result[9] as double?,
      steps: (result[10]! as List<Object?>).cast<SessionStep>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(templateId, other.templateId) && _deepEquals(templateVersion, other.templateVersion) && _deepEquals(name, other.name) && _deepEquals(warmupSeconds, other.warmupSeconds) && _deepEquals(cooldownSeconds, other.cooldownSeconds) && _deepEquals(lapLockout, other.lapLockout) && _deepEquals(autoStop, other.autoStop) && _deepEquals(cueProfile, other.cueProfile) && _deepEquals(hrBandLow, other.hrBandLow) && _deepEquals(hrBandHigh, other.hrBandHigh) && _deepEquals(steps, other.steps);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// One prior run on a live board. Exactly one of the three series is set,
/// by the board's kind: `fromStartSplitsMs` (distance: cumulative ms from
/// the Start press at each whole km, WARN-1), `liveRepPacesSecPerKm`
/// (intervals: untrimmed lap distance / lap time per work rep, null for an
/// unclean rep, BLOCK-2), `cooperMinuteM` (Cooper: cumulative metres at each
/// whole minute of the test).
class LiveEntry {
  LiveEntry({
    required this.runId,
    required this.dateMs,
    this.fromStartSplitsMs,
    this.liveRepPacesSecPerKm,
    this.cooperMinuteM,
    required this.finalMetric,
  });

  String runId;

  /// Run start, epoch millis.
  int dateMs;

  List<int>? fromStartSplitsMs;

  List<double?>? liveRepPacesSecPerKm;

  List<double>? cooperMinuteM;

  /// The board's metric for the whole run (finish ms, mean rep pace s/km,
  /// or raw Cooper VO2), for "your #k of n" at the end.
  double finalMetric;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      dateMs,
      fromStartSplitsMs,
      liveRepPacesSecPerKm,
      cooperMinuteM,
      finalMetric,
    ];
  }

  Object encode() {
    return _toList();  }

  static LiveEntry decode(Object result) {
    result as List<Object?>;
    return LiveEntry(
      runId: result[0]! as String,
      dateMs: result[1]! as int,
      fromStartSplitsMs: (result[2] as List<Object?>?)?.cast<int>(),
      liveRepPacesSecPerKm: (result[3] as List<Object?>?)?.cast<double?>(),
      cooperMinuteM: (result[4] as List<Object?>?)?.cast<double>(),
      finalMetric: result[5]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LiveEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) && _deepEquals(dateMs, other.dateMs) && _deepEquals(fromStartSplitsMs, other.fromStartSplitsMs) && _deepEquals(liveRepPacesSecPerKm, other.liveRepPacesSecPerKm) && _deepEquals(cooperMinuteM, other.cooperMinuteM) && _deepEquals(finalMetric, other.finalMetric);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A board the live compare ranks against: at most 20 entries (top 10 +
/// last 10, deduped). The app only sends a board with 2 or more entries.
class LiveBoard {
  LiveBoard({
    required this.key,
    required this.label,
    required this.kind,
    this.targetM,
    required this.entries,
  });

  /// The comparison key (`be:5000`, an intervals key, `cooper`, a course).
  String key;

  /// Spoken and shown name ("5K", "8 × 400 m"); the app injects any event
  /// name, the engine never writes it.
  String label;

  LiveBoardKind kind;

  /// Distance boards: the board's distance (5000 for a 5K board).
  double? targetM;

  List<LiveEntry> entries;

  List<Object?> _toList() {
    return <Object?>[
      key,
      label,
      kind,
      targetM,
      entries,
    ];
  }

  Object encode() {
    return _toList();  }

  static LiveBoard decode(Object result) {
    result as List<Object?>;
    return LiveBoard(
      key: result[0]! as String,
      label: result[1]! as String,
      kind: result[2]! as LiveBoardKind,
      targetM: result[3] as double?,
      entries: (result[4]! as List<Object?>).cast<LiveEntry>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LiveBoard || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) && _deepEquals(label, other.label) && _deepEquals(kind, other.kind) && _deepEquals(targetM, other.targetM) && _deepEquals(entries, other.entries);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Phase 4 §3.4: a target to race (a predicted time or a recent PB). PD2
/// fills it; even splits over [distanceM].
class LiveTarget {
  LiveTarget({
    required this.distanceM,
    required this.targetMs,
    required this.predicted,
  });

  double distanceM;

  int targetMs;

  /// True = "predicted" (an estimate), false = "your PB".
  bool predicted;

  List<Object?> _toList() {
    return <Object?>[
      distanceM,
      targetMs,
      predicted,
    ];
  }

  Object encode() {
    return _toList();  }

  static LiveTarget decode(Object result) {
    result as List<Object?>;
    return LiveTarget(
      distanceM: result[0]! as double,
      targetMs: result[1]! as int,
      predicted: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LiveTarget || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(distanceM, other.distanceM) && _deepEquals(targetMs, other.targetMs) && _deepEquals(predicted, other.predicted);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// In-run coaching nudges (Phase 4 §3.5). LC1 ships this stub with no rules
/// (WARN-6); CR1 fills it. `version` 0 = no rules.
class NudgePlan {
  NudgePlan({
    required this.version,
  });

  int version;

  List<Object?> _toList() {
    return <Object?>[
      version,
    ];
  }

  Object encode() {
    return _toList();  }

  static NudgePlan decode(Object result) {
    result as List<Object?>;
    return NudgePlan(
      version: result[0]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NudgePlan || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(version, other.version);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Everything the live "you vs you" needs, built by the app at Start within
/// 150 ms or not at all (WARN-3), journaled as the `live_context` line and
/// rebuilt from it on restore (BLOCK-1). Kotlin never reads history.
class LiveContext {
  LiveContext({
    required this.boards,
    this.target,
    this.nudges,
    this.cooperCurve,
    this.cooperHistory,
    required this.coachingMuted,
    required this.builtAtMs,
    required this.engineVersion,
  });

  /// At most 3.
  List<LiveBoard> boards;

  LiveTarget? target;

  NudgePlan? nudges;

  /// Cooper: cumulative fade fractions F(1)..F(12), F(12) = 1 (§3.3).
  List<double>? cooperCurve;

  /// Cooper: past raw VO2 estimates, oldest first (the last is the previous
  /// test, for "up 2 on last time").
  List<double>? cooperHistory;

  bool coachingMuted;

  /// Epoch millis when the app built it.
  int builtAtMs;

  int engineVersion;

  List<Object?> _toList() {
    return <Object?>[
      boards,
      target,
      nudges,
      cooperCurve,
      cooperHistory,
      coachingMuted,
      builtAtMs,
      engineVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static LiveContext decode(Object result) {
    result as List<Object?>;
    return LiveContext(
      boards: (result[0]! as List<Object?>).cast<LiveBoard>(),
      target: result[1] as LiveTarget?,
      nudges: result[2] as NudgePlan?,
      cooperCurve: (result[3] as List<Object?>?)?.cast<double>(),
      cooperHistory: (result[4] as List<Object?>?)?.cast<double>(),
      coachingMuted: result[5]! as bool,
      builtAtMs: result[6]! as int,
      engineVersion: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LiveContext || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(boards, other.boards) && _deepEquals(target, other.target) && _deepEquals(nudges, other.nudges) && _deepEquals(cooperCurve, other.cooperCurve) && _deepEquals(cooperHistory, other.cooperHistory) && _deepEquals(coachingMuted, other.coachingMuted) && _deepEquals(builtAtMs, other.builtAtMs) && _deepEquals(engineVersion, other.engineVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class StartResult {
  StartResult({
    this.runId,
    this.error,
  });

  String? runId;

  StartError? error;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static StartResult decode(Object result) {
    result as List<Object?>;
    return StartResult(
      runId: result[0] as String?,
      error: result[1] as StartError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StartResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// One recorded lap, for a recreated UI (the "last rep" ghost survives an
/// Activity recreate). `distanceM` is the cumulative run distance at the lap.
class LapSummary {
  LapSummary({
    required this.index,
    required this.tMs,
    required this.activeMs,
    required this.distanceM,
    required this.source,
  });

  int index;

  /// Wall time since Start at the lap marker (pauses and gaps included).
  int tMs;

  /// Duration of the lap that ENDS here, excluding pauses and kill gaps —
  /// what the verdict engine's rep time will be.
  int activeMs;

  double distanceM;

  LapSource source;

  List<Object?> _toList() {
    return <Object?>[
      index,
      tMs,
      activeMs,
      distanceM,
      source,
    ];
  }

  Object encode() {
    return _toList();  }

  static LapSummary decode(Object result) {
    result as List<Object?>;
    return LapSummary(
      index: result[0]! as int,
      tMs: result[1]! as int,
      activeMs: result[2]! as int,
      distanceM: result[3]! as double,
      source: result[4]! as LapSource,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LapSummary || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(index, other.index) && _deepEquals(tMs, other.tMs) && _deepEquals(activeMs, other.activeMs) && _deepEquals(distanceM, other.distanceM) && _deepEquals(source, other.source);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Enough for a recreated UI to redraw mid-run.
class RecorderStatus {
  RecorderStatus({
    required this.state,
    this.runId,
    required this.mode,
    required this.laps,
    required this.elapsedMs,
    required this.lapIndex,
    required this.gpsFix,
    required this.hrConnected,
    required this.phase,
    required this.repIndex,
    required this.phaseRemainingMs,
    this.spec,
    this.stepIndex,
    this.stepRemainingMs,
    this.stepRemainingM,
    required this.journalOk,
  });

  RecorderState state;

  String? runId;

  /// The mode picked at Start.
  RecordMode mode;

  List<LapSummary> laps;

  int elapsedMs;

  int lapIndex;

  bool gpsFix;

  bool hrConnected;

  Phase phase;

  int repIndex;

  int phaseRemainingMs;

  SessionSpec? spec;

  /// 0-based index into `spec.steps` during work/recovery; null in warm-up,
  /// cool-down and unstructured runs.
  int? stepIndex;

  int? stepRemainingMs;

  /// Metres left in a distance step (I2; null until then).
  double? stepRemainingM;

  bool journalOk;

  List<Object?> _toList() {
    return <Object?>[
      state,
      runId,
      mode,
      laps,
      elapsedMs,
      lapIndex,
      gpsFix,
      hrConnected,
      phase,
      repIndex,
      phaseRemainingMs,
      spec,
      stepIndex,
      stepRemainingMs,
      stepRemainingM,
      journalOk,
    ];
  }

  Object encode() {
    return _toList();  }

  static RecorderStatus decode(Object result) {
    result as List<Object?>;
    return RecorderStatus(
      state: result[0]! as RecorderState,
      runId: result[1] as String?,
      mode: result[2]! as RecordMode,
      laps: (result[3]! as List<Object?>).cast<LapSummary>(),
      elapsedMs: result[4]! as int,
      lapIndex: result[5]! as int,
      gpsFix: result[6]! as bool,
      hrConnected: result[7]! as bool,
      phase: result[8]! as Phase,
      repIndex: result[9]! as int,
      phaseRemainingMs: result[10]! as int,
      spec: result[11] as SessionSpec?,
      stepIndex: result[12] as int?,
      stepRemainingMs: result[13] as int?,
      stepRemainingM: result[14] as double?,
      journalOk: result[15]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecorderStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(runId, other.runId) && _deepEquals(mode, other.mode) && _deepEquals(laps, other.laps) && _deepEquals(elapsedMs, other.elapsedMs) && _deepEquals(lapIndex, other.lapIndex) && _deepEquals(gpsFix, other.gpsFix) && _deepEquals(hrConnected, other.hrConnected) && _deepEquals(phase, other.phase) && _deepEquals(repIndex, other.repIndex) && _deepEquals(phaseRemainingMs, other.phaseRemainingMs) && _deepEquals(spec, other.spec) && _deepEquals(stepIndex, other.stepIndex) && _deepEquals(stepRemainingMs, other.stepRemainingMs) && _deepEquals(stepRemainingM, other.stepRemainingM) && _deepEquals(journalOk, other.journalOk);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// An in-progress journal found on app open without a finalised run file.
class OrphanJournal {
  OrphanJournal({
    required this.runId,
    required this.lastLineAgeMs,
    required this.mode,
    required this.readable,
    required this.newer,
    required this.endedPaused,
    required this.elapsedMs,
  });

  String runId;

  int lastLineAgeMs;

  RecordMode mode;

  /// False when the journal has no decodable header: it can only be discarded
  /// (unless `newer`).
  bool readable;

  /// The journal was written by a newer app (schema or mode this build does not
  /// know). Unreadable here, but NEVER offered for discard: show "update the
  /// app to recover this run"; `discardJournal` refuses it (plan §18.7 W6).
  bool newer;

  /// The run was paused when the process died.
  bool endedPaused;

  /// Run time recorded before the kill (pauses and earlier gaps included).
  int elapsedMs;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      lastLineAgeMs,
      mode,
      readable,
      newer,
      endedPaused,
      elapsedMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static OrphanJournal decode(Object result) {
    result as List<Object?>;
    return OrphanJournal(
      runId: result[0]! as String,
      lastLineAgeMs: result[1]! as int,
      mode: result[2]! as RecordMode,
      readable: result[3]! as bool,
      newer: result[4]! as bool,
      endedPaused: result[5]! as bool,
      elapsedMs: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OrphanJournal || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) && _deepEquals(lastLineAgeMs, other.lastLineAgeMs) && _deepEquals(mode, other.mode) && _deepEquals(readable, other.readable) && _deepEquals(newer, other.newer) && _deepEquals(endedPaused, other.endedPaused) && _deepEquals(elapsedMs, other.elapsedMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Replay mode (plan §12; debug builds only): a fixture trace fed through the
/// recorder at `speed`x on a virtual clock. `fixture` is `synthetic-4x4`
/// (straight line: 60 s warmup, the spec's steps, 60 s cooldown, HR by phase)
/// or the name of a CSV under the app's Android `assets/replay/`.
class ReplayConfig {
  ReplayConfig({
    required this.fixture,
    required this.speed,
  });

  String fixture;

  double speed;

  List<Object?> _toList() {
    return <Object?>[
      fixture,
      speed,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReplayConfig decode(Object result) {
    result as List<Object?>;
    return ReplayConfig(
      fixture: result[0]! as String,
      speed: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReplayConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fixture, other.fixture) && _deepEquals(speed, other.speed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Everything the setup checklist shows (plan §9, §10).
class PermissionStatus {
  PermissionStatus({
    required this.fineLocation,
    required this.approximateOnly,
    required this.locationEnabled,
    required this.notifications,
    required this.bluetooth,
    required this.batteryUnrestricted,
    required this.gmsAvailable,
  });

  bool fineLocation;

  /// Coarse granted without fine: recording would silently be indoor (W10).
  bool approximateOnly;

  bool locationEnabled;

  /// Granted, or not needed (API < 33).
  bool notifications;

  /// SCAN + CONNECT granted, or not needed (API < 31).
  bool bluetooth;

  /// Not under battery optimisation; false → checklist deep-links to the page.
  bool batteryUnrestricted;

  /// FusedLocationProvider available; false → raw GPS_PROVIDER fallback.
  bool gmsAvailable;

  List<Object?> _toList() {
    return <Object?>[
      fineLocation,
      approximateOnly,
      locationEnabled,
      notifications,
      bluetooth,
      batteryUnrestricted,
      gmsAvailable,
    ];
  }

  Object encode() {
    return _toList();  }

  static PermissionStatus decode(Object result) {
    result as List<Object?>;
    return PermissionStatus(
      fineLocation: result[0]! as bool,
      approximateOnly: result[1]! as bool,
      locationEnabled: result[2]! as bool,
      notifications: result[3]! as bool,
      bluetooth: result[4]! as bool,
      batteryUnrestricted: result[5]! as bool,
      gmsAvailable: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PermissionStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fineLocation, other.fineLocation) && _deepEquals(approximateOnly, other.approximateOnly) && _deepEquals(locationEnabled, other.locationEnabled) && _deepEquals(notifications, other.notifications) && _deepEquals(bluetooth, other.bluetooth) && _deepEquals(batteryUnrestricted, other.batteryUnrestricted) && _deepEquals(gmsAvailable, other.gmsAvailable);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class BleStatus {
  BleStatus({
    required this.connected,
    this.address,
    this.name,
    this.lastHr,
    required this.adapterOn,
  });

  bool connected;

  String? address;

  String? name;

  int? lastHr;

  bool adapterOn;

  List<Object?> _toList() {
    return <Object?>[
      connected,
      address,
      name,
      lastHr,
      adapterOn,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleStatus decode(Object result) {
    result as List<Object?>;
    return BleStatus(
      connected: result[0]! as bool,
      address: result[1] as String?,
      name: result[2] as String?,
      lastHr: result[3] as int?,
      adapterOn: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(connected, other.connected) && _deepEquals(address, other.address) && _deepEquals(name, other.name) && _deepEquals(lastHr, other.lastHr) && _deepEquals(adapterOn, other.adapterOn);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Result of the OS-kill diagnosis for a run (plan §3, W11).
class ExitDiagnosis {
  ExitDiagnosis({
    required this.runId,
    required this.reason,
    required this.timestampMs,
    this.description,
    required this.manufacturer,
  });

  String runId;

  ExitReason reason;

  /// Wall-clock epoch ms of the kill, 0 when none.
  int timestampMs;

  /// Raw `ApplicationExitInfo.description`, for the diagnostics screen.
  String? description;

  /// `Build.MANUFACTURER` lower-cased, so the UI picks per-OEM guidance.
  String manufacturer;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      reason,
      timestampMs,
      description,
      manufacturer,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExitDiagnosis decode(Object result) {
    result as List<Object?>;
    return ExitDiagnosis(
      runId: result[0]! as String,
      reason: result[1]! as ExitReason,
      timestampMs: result[2]! as int,
      description: result[3] as String?,
      manufacturer: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExitDiagnosis || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) && _deepEquals(reason, other.reason) && _deepEquals(timestampMs, other.timestampMs) && _deepEquals(description, other.description) && _deepEquals(manufacturer, other.manufacturer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class BleDevice {
  BleDevice({
    required this.address,
    this.name,
  });

  String address;

  String? name;

  List<Object?> _toList() {
    return <Object?>[
      address,
      name,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleDevice decode(Object result) {
    result as List<Object?>;
    return BleDevice(
      address: result[0]! as String,
      name: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) && _deepEquals(name, other.name);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// What the static Auto Backup rules would back up right now (plan §4, W3):
/// `databases/runsolo.db` + `files/runs/` run files + sidecars. `files/state/`
/// is a few KB and not counted. Over the 25 MB `quotaBytes` Android backs up
/// nothing, so the app keeps the set under `budgetBytes` (15 MB) by archiving.
class BackupStatus {
  BackupStatus({
    required this.backedUpBytes,
    required this.budgetBytes,
    required this.quotaBytes,
    required this.archivedRunCount,
    required this.overBudget,
  });

  int backedUpBytes;

  int budgetBytes;

  int quotaBytes;

  /// Runs already in `files/runs-archive/` (on device, indexed, not backed up).
  int archivedRunCount;

  bool overBudget;

  List<Object?> _toList() {
    return <Object?>[
      backedUpBytes,
      budgetBytes,
      quotaBytes,
      archivedRunCount,
      overBudget,
    ];
  }

  Object encode() {
    return _toList();  }

  static BackupStatus decode(Object result) {
    result as List<Object?>;
    return BackupStatus(
      backedUpBytes: result[0]! as int,
      budgetBytes: result[1]! as int,
      quotaBytes: result[2]! as int,
      archivedRunCount: result[3]! as int,
      overBudget: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BackupStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(backedUpBytes, other.backedUpBytes) && _deepEquals(budgetBytes, other.budgetBytes) && _deepEquals(quotaBytes, other.quotaBytes) && _deepEquals(archivedRunCount, other.archivedRunCount) && _deepEquals(overBudget, other.overBudget);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

sealed class RecorderEvent {
}

class TickEvent extends RecorderEvent {
  TickEvent({
    required this.elapsedMs,
    required this.lapElapsedMs,
    required this.lapDistanceM,
    this.lapPaceLiveSecPerKm,
    required this.totalDistanceM,
    this.hr,
    this.gpsAccuracyM,
    required this.state,
    required this.phase,
    required this.repIndex,
    required this.phaseRemainingMs,
    this.stepIndex,
    this.stepRemainingMs,
    this.stepRemainingM,
  });

  /// Wall time since Start, pauses included.
  int elapsedMs;

  int lapElapsedMs;

  /// Distance since the last lap marker (`totalDistanceM` is cumulative).
  double lapDistanceM;

  /// Rolling 15 s "live" pace; differs from the verdict's trimmed pace.
  double? lapPaceLiveSecPerKm;

  double totalDistanceM;

  int? hr;

  double? gpsAccuracyM;

  RecorderState state;

  Phase phase;

  int repIndex;

  /// Active-time countdown of the current timed phase (0 when untimed).
  int phaseRemainingMs;

  /// As `RecorderStatus`: the 0-based step (null in warm-up/cool-down), the
  /// time left in a time step, the metres left in a distance step (whose
  /// `phaseRemainingMs` is 0).
  int? stepIndex;

  int? stepRemainingMs;

  double? stepRemainingM;

  List<Object?> _toList() {
    return <Object?>[
      elapsedMs,
      lapElapsedMs,
      lapDistanceM,
      lapPaceLiveSecPerKm,
      totalDistanceM,
      hr,
      gpsAccuracyM,
      state,
      phase,
      repIndex,
      phaseRemainingMs,
      stepIndex,
      stepRemainingMs,
      stepRemainingM,
    ];
  }

  Object encode() {
    return _toList();  }

  static TickEvent decode(Object result) {
    result as List<Object?>;
    return TickEvent(
      elapsedMs: result[0]! as int,
      lapElapsedMs: result[1]! as int,
      lapDistanceM: result[2]! as double,
      lapPaceLiveSecPerKm: result[3] as double?,
      totalDistanceM: result[4]! as double,
      hr: result[5] as int?,
      gpsAccuracyM: result[6] as double?,
      state: result[7]! as RecorderState,
      phase: result[8]! as Phase,
      repIndex: result[9]! as int,
      phaseRemainingMs: result[10]! as int,
      stepIndex: result[11] as int?,
      stepRemainingMs: result[12] as int?,
      stepRemainingM: result[13] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TickEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(elapsedMs, other.elapsedMs) && _deepEquals(lapElapsedMs, other.lapElapsedMs) && _deepEquals(lapDistanceM, other.lapDistanceM) && _deepEquals(lapPaceLiveSecPerKm, other.lapPaceLiveSecPerKm) && _deepEquals(totalDistanceM, other.totalDistanceM) && _deepEquals(hr, other.hr) && _deepEquals(gpsAccuracyM, other.gpsAccuracyM) && _deepEquals(state, other.state) && _deepEquals(phase, other.phase) && _deepEquals(repIndex, other.repIndex) && _deepEquals(phaseRemainingMs, other.phaseRemainingMs) && _deepEquals(stepIndex, other.stepIndex) && _deepEquals(stepRemainingMs, other.stepRemainingMs) && _deepEquals(stepRemainingM, other.stepRemainingM);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class LapEvent extends RecorderEvent {
  LapEvent({
    required this.index,
    required this.tMs,
    required this.activeMs,
    required this.distanceM,
    required this.source,
  });

  int index;

  int tMs;

  /// Duration of the lap that ends here, excluding pauses and kill gaps.
  int activeMs;

  double distanceM;

  LapSource source;

  List<Object?> _toList() {
    return <Object?>[
      index,
      tMs,
      activeMs,
      distanceM,
      source,
    ];
  }

  Object encode() {
    return _toList();  }

  static LapEvent decode(Object result) {
    result as List<Object?>;
    return LapEvent(
      index: result[0]! as int,
      tMs: result[1]! as int,
      activeMs: result[2]! as int,
      distanceM: result[3]! as double,
      source: result[4]! as LapSource,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LapEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(index, other.index) && _deepEquals(tMs, other.tMs) && _deepEquals(activeMs, other.activeMs) && _deepEquals(distanceM, other.distanceM) && _deepEquals(source, other.source);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A manual lap (button, notification, volume key, "Start reps") the core
/// accepted, sent at the press. The [LapEvent] with the same [index] follows
/// on the next tick (up to 1 s later, so its distance is interpolated at the
/// press); until then the UI shows the new lap from this. [endedPhase] and
/// [endedRepIndex] are the phase the lap closes, so the lap's pace is
/// attributed by the lap itself, never by arrival order. [nextPhase] is set
/// when the lap re-aligns a structured session (its [PhaseEvent] also
/// follows the [LapEvent]).
class LapPendingEvent extends RecorderEvent {
  LapPendingEvent({
    required this.index,
    required this.tMs,
    required this.activeMs,
    required this.source,
    required this.endedPhase,
    required this.endedRepIndex,
    this.nextPhase,
    this.nextRepIndex,
    this.nextPhaseDurationMs,
  });

  int index;

  int tMs;

  int activeMs;

  LapSource source;

  Phase endedPhase;

  int endedRepIndex;

  Phase? nextPhase;

  int? nextRepIndex;

  /// 0 for untimed phases, like [PhaseEvent.phaseDurationMs].
  int? nextPhaseDurationMs;

  List<Object?> _toList() {
    return <Object?>[
      index,
      tMs,
      activeMs,
      source,
      endedPhase,
      endedRepIndex,
      nextPhase,
      nextRepIndex,
      nextPhaseDurationMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static LapPendingEvent decode(Object result) {
    result as List<Object?>;
    return LapPendingEvent(
      index: result[0]! as int,
      tMs: result[1]! as int,
      activeMs: result[2]! as int,
      source: result[3]! as LapSource,
      endedPhase: result[4]! as Phase,
      endedRepIndex: result[5]! as int,
      nextPhase: result[6] as Phase?,
      nextRepIndex: result[7] as int?,
      nextPhaseDurationMs: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LapPendingEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(index, other.index) && _deepEquals(tMs, other.tMs) && _deepEquals(activeMs, other.activeMs) && _deepEquals(source, other.source) && _deepEquals(endedPhase, other.endedPhase) && _deepEquals(endedRepIndex, other.endedRepIndex) && _deepEquals(nextPhase, other.nextPhase) && _deepEquals(nextRepIndex, other.nextRepIndex) && _deepEquals(nextPhaseDurationMs, other.nextPhaseDurationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CueEvent extends RecorderEvent {
  CueEvent({
    required this.kind,
    this.value,
  });

  CueKind kind;

  /// `projection`: the projected Cooper distance in metres, or a distance
  /// step's projected finish in ms; `minuteMark`: the minute. Null otherwise.
  double? value;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static CueEvent decode(Object result) {
    result as List<Object?>;
    return CueEvent(
      kind: result[0]! as CueKind,
      value: result[1] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CueEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Pre-start GPS readiness, about 1 Hz while the probe runs. The "ready"
/// threshold is the screen's; native sends the raw values.
class GpsProbeEvent extends RecorderEvent {
  GpsProbeEvent({
    required this.fix,
    this.lat,
    this.lon,
    this.accuracyM,
    this.fixAgeMs,
  });

  /// A location arrived within the last 5 s.
  bool fix;

  /// Where the runner is now (with a fresh fix only): the app picks the event
  /// course by its nearest known start. In memory only; nothing is stored
  /// until the run records.
  double? lat;

  double? lon;

  /// That fix's accuracy (m); null without a fresh fix.
  double? accuracyM;

  /// How long ago the last fix arrived; null if none yet.
  int? fixAgeMs;

  List<Object?> _toList() {
    return <Object?>[
      fix,
      lat,
      lon,
      accuracyM,
      fixAgeMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static GpsProbeEvent decode(Object result) {
    result as List<Object?>;
    return GpsProbeEvent(
      fix: result[0]! as bool,
      lat: result[1] as double?,
      lon: result[2] as double?,
      accuracyM: result[3] as double?,
      fixAgeMs: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GpsProbeEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fix, other.fix) && _deepEquals(lat, other.lat) && _deepEquals(lon, other.lon) && _deepEquals(accuracyM, other.accuracyM) && _deepEquals(fixAgeMs, other.fixAgeMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class FaultEvent extends RecorderEvent {
  FaultEvent({
    required this.kind,
    required this.message,
  });

  FaultKind kind;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static FaultEvent decode(Object result) {
    result as List<Object?>;
    return FaultEvent(
      kind: result[0]! as FaultKind,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FaultEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Recorder state transitions (start, pause, resume, stop, finalised), so a UI
/// that missed a tick still redraws; `status()` remains the source of truth.
class StateEvent extends RecorderEvent {
  StateEvent({
    required this.state,
    this.runId,
    required this.phase,
  });

  RecorderState state;

  String? runId;

  Phase phase;

  List<Object?> _toList() {
    return <Object?>[
      state,
      runId,
      phase,
    ];
  }

  Object encode() {
    return _toList();  }

  static StateEvent decode(Object result) {
    result as List<Object?>;
    return StateEvent(
      state: result[0]! as RecorderState,
      runId: result[1] as String?,
      phase: result[2]! as Phase,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(runId, other.runId) && _deepEquals(phase, other.phase);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Phase change (warmup -> work 1 -> recovery 1 -> ... -> cooldown).
class PhaseEvent extends RecorderEvent {
  PhaseEvent({
    required this.phase,
    required this.repIndex,
    required this.phaseDurationMs,
  });

  Phase phase;

  int repIndex;

  /// 0 for untimed phases (warmup, cooldown).
  int phaseDurationMs;

  List<Object?> _toList() {
    return <Object?>[
      phase,
      repIndex,
      phaseDurationMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static PhaseEvent decode(Object result) {
    result as List<Object?>;
    return PhaseEvent(
      phase: result[0]! as Phase,
      repIndex: result[1]! as int,
      phaseDurationMs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PhaseEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(phase, other.phase) && _deepEquals(repIndex, other.repIndex) && _deepEquals(phaseDurationMs, other.phaseDurationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RecordMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is Units) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is RecorderState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is Phase) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is LapSource) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is CueKind) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is StepKind) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is TargetKind) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is RecoveryStyle) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is CueProfile) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is FaultKind) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    }    else if (value is StartError) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    }    else if (value is PermissionKind) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    }    else if (value is ExitReason) {
      buffer.putUint8(142);
      writeValue(buffer, value.index);
    }    else if (value is LiveBoardKind) {
      buffer.putUint8(143);
      writeValue(buffer, value.index);
    }    else if (value is SessionStep) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is SessionSpec) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is LiveEntry) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is LiveBoard) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is LiveTarget) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is NudgePlan) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is LiveContext) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is StartResult) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is LapSummary) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    }    else if (value is RecorderStatus) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    }    else if (value is OrphanJournal) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    }    else if (value is ReplayConfig) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    }    else if (value is PermissionStatus) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    }    else if (value is BleStatus) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    }    else if (value is ExitDiagnosis) {
      buffer.putUint8(158);
      writeValue(buffer, value.encode());
    }    else if (value is BleDevice) {
      buffer.putUint8(159);
      writeValue(buffer, value.encode());
    }    else if (value is BackupStatus) {
      buffer.putUint8(160);
      writeValue(buffer, value.encode());
    }    else if (value is TickEvent) {
      buffer.putUint8(161);
      writeValue(buffer, value.encode());
    }    else if (value is LapEvent) {
      buffer.putUint8(162);
      writeValue(buffer, value.encode());
    }    else if (value is LapPendingEvent) {
      buffer.putUint8(163);
      writeValue(buffer, value.encode());
    }    else if (value is CueEvent) {
      buffer.putUint8(164);
      writeValue(buffer, value.encode());
    }    else if (value is GpsProbeEvent) {
      buffer.putUint8(165);
      writeValue(buffer, value.encode());
    }    else if (value is FaultEvent) {
      buffer.putUint8(166);
      writeValue(buffer, value.encode());
    }    else if (value is StateEvent) {
      buffer.putUint8(167);
      writeValue(buffer, value.encode());
    }    else if (value is PhaseEvent) {
      buffer.putUint8(168);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RecordMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : Units.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : RecorderState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : Phase.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : LapSource.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : CueKind.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : StepKind.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : TargetKind.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : RecoveryStyle.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : CueProfile.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : FaultKind.values[value];
      case 140:
        final value = readValue(buffer) as int?;
        return value == null ? null : StartError.values[value];
      case 141:
        final value = readValue(buffer) as int?;
        return value == null ? null : PermissionKind.values[value];
      case 142:
        final value = readValue(buffer) as int?;
        return value == null ? null : ExitReason.values[value];
      case 143:
        final value = readValue(buffer) as int?;
        return value == null ? null : LiveBoardKind.values[value];
      case 144:
        return SessionStep.decode(readValue(buffer)!);
      case 145:
        return SessionSpec.decode(readValue(buffer)!);
      case 146:
        return LiveEntry.decode(readValue(buffer)!);
      case 147:
        return LiveBoard.decode(readValue(buffer)!);
      case 148:
        return LiveTarget.decode(readValue(buffer)!);
      case 149:
        return NudgePlan.decode(readValue(buffer)!);
      case 150:
        return LiveContext.decode(readValue(buffer)!);
      case 151:
        return StartResult.decode(readValue(buffer)!);
      case 152:
        return LapSummary.decode(readValue(buffer)!);
      case 153:
        return RecorderStatus.decode(readValue(buffer)!);
      case 154:
        return OrphanJournal.decode(readValue(buffer)!);
      case 155:
        return ReplayConfig.decode(readValue(buffer)!);
      case 156:
        return PermissionStatus.decode(readValue(buffer)!);
      case 157:
        return BleStatus.decode(readValue(buffer)!);
      case 158:
        return ExitDiagnosis.decode(readValue(buffer)!);
      case 159:
        return BleDevice.decode(readValue(buffer)!);
      case 160:
        return BackupStatus.decode(readValue(buffer)!);
      case 161:
        return TickEvent.decode(readValue(buffer)!);
      case 162:
        return LapEvent.decode(readValue(buffer)!);
      case 163:
        return LapPendingEvent.decode(readValue(buffer)!);
      case 164:
        return CueEvent.decode(readValue(buffer)!);
      case 165:
        return GpsProbeEvent.decode(readValue(buffer)!);
      case 166:
        return FaultEvent.decode(readValue(buffer)!);
      case 167:
        return StateEvent.decode(readValue(buffer)!);
      case 168:
        return PhaseEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class RecorderApi {
  /// Constructor for [RecorderApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RecorderApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Idempotent: a second call while recording returns the running id. Must be
  /// called while the Activity is visible (the FGS is started from it, B2).
  ///
  /// `spec`: required for `intervals` and `cooper`, the fartlek spec or null
  /// for `laps`, null for `free`; anything else is `unsupportedSession`.
  /// `liveContext`: the history the live compare needs (Phase 4 §3.2; Kotlin
  /// does not read history), journaled as the `live_context` line after the
  /// header; null = no compare, no overlay, no nudges, nothing said. The
  /// previous Cooper VO2 for "up 2 on last time" is the last
  /// `cooperHistory` entry.
  Future<StartResult> start(RecordMode mode, SessionSpec? spec, Units units, LiveContext? liveContext) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode, spec, units, liveContext]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as StartResult;
  }

  /// Debug builds only: like `start`, fed from a fixture instead of GPS/BLE.
  Future<StartResult> startReplay(RecordMode mode, SessionSpec? spec, Units units, ReplayConfig replay) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.startReplay$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode, spec, units, replay]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as StartResult;
  }

  /// Continue an orphaned journal after the user confirms (plan §3): writes the
  /// `gap` line, rebuilds the step phase from the journal, restarts the FGS.
  /// Idempotent like `start`.
  Future<StartResult> resumeRecovered(String runId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.resumeRecovered$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[runId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as StartResult;
  }

  Future<void> pause() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> resume() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.resume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> lap(LapSource source) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.lap$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// The "Start reps" action: ends the untimed warm-up and starts rep 1 (same
  /// effect and journal line as a first `lap(button)`); a no-op anywhere else,
  /// so a manual LAP mid-rep can never be confused with starting.
  Future<void> startReps() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.startReps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Finalises in Kotlin (journal -> tmp -> fsync -> rename -> delete journal). No-op when idle.
  Future<String?> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<RecorderStatus> status() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as RecorderStatus;
  }

  /// Called on app open: journals without a finalised file, newest first. Never
  /// includes the run that is being recorded.
  Future<List<OrphanJournal>> recover() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.recover$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<OrphanJournal>();
  }

  /// Finalise an orphaned journal without resuming it. Returns the run file
  /// path relative to the app's files dir, or null when nothing was there.
  Future<String?> finalise(String runId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.finalise$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[runId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// Delete an unreadable orphan (`readable == false`). Never touches a run file.
  Future<void> discardJournal(String runId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.discardJournal$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[runId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setCues(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.setCues$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Pre-start location readiness (the Start screen): fixes with the
  /// recording's provider settings, a [GpsProbeEvent] about once a second.
  /// Idempotent. Stopped by [stopGpsProbe], by any start, and when the app
  /// leaves the foreground; foreground only, no service.
  Future<void> startGpsProbe() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.startGpsProbe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stopGpsProbe() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.stopGpsProbe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// The user's volume-key LAP setting for Laps runs, persisted natively (the
  /// recorder reads it at start). Takes effect from the next run or resume,
  /// not the live one. Unset means on. Intervals, Free and Cooper never use
  /// volume keys, whatever this says. A no-op in effect where
  /// `PermissionsApi.volumeKeyLapsSupported()` is false.
  Future<void> setVolumeKeyLaps(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.setVolumeKeyLaps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Run files on disk (`runs/` + `runs-archive/`) as `runId -> relative path`,
  /// for the Dart Reconciler. Journals and sidecars are not listed.
  Future<Map<String, String>> listRunFiles() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.listRunFiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, String>();
  }

  /// Was the previous process killed by the OS while `runId` was recording?
  Future<ExitDiagnosis> exitDiagnosis(String runId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.exitDiagnosis$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[runId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ExitDiagnosis;
  }
}

/// Backup budget (plan §4). Journals live in `files/journals/`, run files in
/// `files/runs/`, overflow in `files/runs-archive/`; the rules files exclude
/// journals, the archive and the SQLite `-wal`/`-shm`/`-journal` side files.
class StorageApi {
  /// Constructor for [StorageApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  StorageApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<BackupStatus> backupStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.StorageApi.backupStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BackupStatus;
  }

  /// Moves the oldest run files (with their sidecars) into `runs-archive/`
  /// until the backed-up set fits the budget; returns the run ids moved. Call
  /// after each finalise/import, then run the Reconciler (rows get `repath`).
  /// Non-empty → show "export to keep older runs safe". Never touches the run
  /// being recorded, never deletes anything.
  Future<List<String>> enforceBackupBudget() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.StorageApi.enforceBackupBudget$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }
}

class PermissionsApi {
  /// Constructor for [PermissionsApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PermissionsApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<PermissionStatus> permissionStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.permissionStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PermissionStatus;
  }

  /// Shows the system prompt (or the enable-location dialog for `location` when
  /// the setting is off). Resolves when the user answers; true = granted.
  Future<bool> requestPermission(PermissionKind kind) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.requestPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[kind]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// The only Settings deep link allowed (plan §10): the app's battery page.
  /// The setup checklist's battery step opens this and re-reads
  /// `batteryUnrestricted`; the direct REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
  /// dialog is not used (Play flags the declaration for this app type).
  Future<void> openBatterySettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.openBatterySettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openAppSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.openAppSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// `FLAG_KEEP_SCREEN_ON` on the Activity window (design brief: screen stays
  /// on while recording, user setting). Cleared automatically when the
  /// Activity is recreated, so call it again from the recording screen.
  Future<void> setKeepScreenOn(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.setKeepScreenOn$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Whether volume keys can land laps on this device. False on Android 14
  /// (API 34), where keys never reach an app's session: hide the volume-key
  /// LAP setting there and point at the lock-screen LAP instead.
  Future<bool> volumeKeyLapsSupported() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.volumeKeyLapsSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}

class BleApi {
  /// Constructor for [BleApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BleApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Scan once for Heart Rate Profile (0x180D) devices to pair (≤ 10 s).
  Future<List<BleDevice>> bleScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.BleApi.bleScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<BleDevice>();
  }

  /// Saves the address and connects; reconnects use autoConnect, never a rescan.
  Future<void> blePair(String address) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.BleApi.blePair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> bleForget() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.BleApi.bleForget$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<BleStatus> bleStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.BleApi.bleStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BleStatus;
  }
}

Stream<RecorderEvent> recorderEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel recorderEventsChannel =
      EventChannel('dev.flutter.pigeon.run_solo.RecorderEvents.recorderEvents$instanceName', pigeonMethodCodec);
  return recorderEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as RecorderEvent;
  });
}
    
