// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Mode picked at Start. Mirrors `RunMode` in `package:run_engine`.
enum RecordMode {
  fourByFour,
  free,
}

enum Units {
  km,
  mi,
}

enum RecorderState {
  idle,
  recording,
  paused,
  finalising,
}

/// Phase of a preset (4x4) run; `none` in free mode or outside a rep.
enum Phase {
  none,
  warmup,
  work,
  recovery,
  cooldown,
}

enum LapSource {
  button,
  notification,
  volumeKey,
  auto,
}

enum CueKind {
  halfway,
  thirtySeconds,
  phaseEnd,
  start,
  stop,
}

enum FaultKind {
  gpsLost,
  gpsWeak,
  hrDisconnected,
  journalWriteFailed,
  lowStorage,
  /// The OS killed the process mid-run (read from ApplicationExitInfo on the
  /// next app open); the UI shows the OEM guidance from `exitDiagnosis`.
  osKilledMidRun,
  /// The foreground service could not start after `start` returned a run id;
  /// the run was discarded (no file). Show the message, return to Start.
  startFailed,
}

/// Typed errors returned by `start` (plan §2). Never a stringly-typed map.
enum StartError {
  noFinePermission,
  approximateOnly,
  locationOff,
  lowStorage,
  notificationsDenied,
  alreadyRunning,
  /// `startReplay` on a release build, or an unknown fixture name.
  replayUnavailable,
  /// `resumeRecovered` for a journal that no longer exists or is unreadable.
  noSuchJournal,
  /// The OS refused the location foreground service (Android 14+ background
  /// start, or the permission was revoked between check and start). Nothing
  /// was recorded; no run file is written.
  fgsNotAllowed,
}

/// Runtime permissions the setup checklist can request (plan §10). Location is
/// the system prompt only (never a deep link); bluetooth = SCAN + CONNECT on
/// API 31+, nothing to request below.
enum PermissionKind {
  location,
  notifications,
  bluetooth,
}

/// Why the previous process died, from `ApplicationExitInfo` (API 30+).
enum ExitReason {
  /// No kill recorded for this run (normal stop, or API 29).
  none,
  osKilled,
  lowMemory,
  crash,
  userStop,
  other,
}

/// The 4x4 preset written into the file header; drives cues and the detector.
class Preset {
  Preset({
    required this.reps,
    required this.workSeconds,
    required this.recoverySeconds,
  });

  int reps;

  int workSeconds;

  int recoverySeconds;

  List<Object?> _toList() {
    return <Object?>[
      reps,
      workSeconds,
      recoverySeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static Preset decode(Object result) {
    result as List<Object?>;
    return Preset(
      reps: result[0]! as int,
      workSeconds: result[1]! as int,
      recoverySeconds: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Preset || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(reps, other.reps) && _deepEquals(workSeconds, other.workSeconds) && _deepEquals(recoverySeconds, other.recoverySeconds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class StartResult {
  StartResult({
    this.runId,
    this.error,
  });

  String? runId;

  StartError? error;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static StartResult decode(Object result) {
    result as List<Object?>;
    return StartResult(
      runId: result[0] as String?,
      error: result[1] as StartError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StartResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Enough for a recreated UI to redraw mid-run.
class RecorderStatus {
  RecorderStatus({
    required this.state,
    this.runId,
    required this.elapsedMs,
    required this.lapIndex,
    required this.gpsFix,
    required this.hrConnected,
    required this.phase,
    required this.repIndex,
    required this.phaseRemainingMs,
    this.preset,
    required this.journalOk,
  });

  RecorderState state;

  String? runId;

  int elapsedMs;

  int lapIndex;

  bool gpsFix;

  bool hrConnected;

  Phase phase;

  int repIndex;

  int phaseRemainingMs;

  Preset? preset;

  bool journalOk;

  List<Object?> _toList() {
    return <Object?>[
      state,
      runId,
      elapsedMs,
      lapIndex,
      gpsFix,
      hrConnected,
      phase,
      repIndex,
      phaseRemainingMs,
      preset,
      journalOk,
    ];
  }

  Object encode() {
    return _toList();  }

  static RecorderStatus decode(Object result) {
    result as List<Object?>;
    return RecorderStatus(
      state: result[0]! as RecorderState,
      runId: result[1] as String?,
      elapsedMs: result[2]! as int,
      lapIndex: result[3]! as int,
      gpsFix: result[4]! as bool,
      hrConnected: result[5]! as bool,
      phase: result[6]! as Phase,
      repIndex: result[7]! as int,
      phaseRemainingMs: result[8]! as int,
      preset: result[9] as Preset?,
      journalOk: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecorderStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(runId, other.runId) && _deepEquals(elapsedMs, other.elapsedMs) && _deepEquals(lapIndex, other.lapIndex) && _deepEquals(gpsFix, other.gpsFix) && _deepEquals(hrConnected, other.hrConnected) && _deepEquals(phase, other.phase) && _deepEquals(repIndex, other.repIndex) && _deepEquals(phaseRemainingMs, other.phaseRemainingMs) && _deepEquals(preset, other.preset) && _deepEquals(journalOk, other.journalOk);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// An in-progress journal found on app open without a finalised run file.
class OrphanJournal {
  OrphanJournal({
    required this.runId,
    required this.lastLineAgeMs,
    required this.mode,
    required this.readable,
    required this.endedPaused,
    required this.elapsedMs,
  });

  String runId;

  int lastLineAgeMs;

  RecordMode mode;

  /// False when the journal has no decodable header: it can only be discarded.
  bool readable;

  /// The run was paused when the process died.
  bool endedPaused;

  /// Run time recorded before the kill (pauses and earlier gaps included).
  int elapsedMs;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      lastLineAgeMs,
      mode,
      readable,
      endedPaused,
      elapsedMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static OrphanJournal decode(Object result) {
    result as List<Object?>;
    return OrphanJournal(
      runId: result[0]! as String,
      lastLineAgeMs: result[1]! as int,
      mode: result[2]! as RecordMode,
      readable: result[3]! as bool,
      endedPaused: result[4]! as bool,
      elapsedMs: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OrphanJournal || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) && _deepEquals(lastLineAgeMs, other.lastLineAgeMs) && _deepEquals(mode, other.mode) && _deepEquals(readable, other.readable) && _deepEquals(endedPaused, other.endedPaused) && _deepEquals(elapsedMs, other.elapsedMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Replay mode (plan §12; debug builds only): a fixture trace fed through the
/// recorder at `speed`x on a virtual clock. `fixture` is `synthetic-4x4`
/// (straight line: 60 s warmup, the preset's reps, 60 s cooldown, HR by phase)
/// or the name of a CSV under the app's Android `assets/replay/`.
class ReplayConfig {
  ReplayConfig({
    required this.fixture,
    required this.speed,
  });

  String fixture;

  double speed;

  List<Object?> _toList() {
    return <Object?>[
      fixture,
      speed,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReplayConfig decode(Object result) {
    result as List<Object?>;
    return ReplayConfig(
      fixture: result[0]! as String,
      speed: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReplayConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fixture, other.fixture) && _deepEquals(speed, other.speed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Everything the setup checklist shows (plan §9, §10).
class PermissionStatus {
  PermissionStatus({
    required this.fineLocation,
    required this.approximateOnly,
    required this.locationEnabled,
    required this.notifications,
    required this.bluetooth,
    required this.batteryUnrestricted,
    required this.gmsAvailable,
  });

  bool fineLocation;

  /// Coarse granted without fine: recording would silently be indoor (W10).
  bool approximateOnly;

  bool locationEnabled;

  /// Granted, or not needed (API < 33).
  bool notifications;

  /// SCAN + CONNECT granted, or not needed (API < 31).
  bool bluetooth;

  /// Not under battery optimisation; false → checklist deep-links to the page.
  bool batteryUnrestricted;

  /// FusedLocationProvider available; false → raw GPS_PROVIDER fallback.
  bool gmsAvailable;

  List<Object?> _toList() {
    return <Object?>[
      fineLocation,
      approximateOnly,
      locationEnabled,
      notifications,
      bluetooth,
      batteryUnrestricted,
      gmsAvailable,
    ];
  }

  Object encode() {
    return _toList();  }

  static PermissionStatus decode(Object result) {
    result as List<Object?>;
    return PermissionStatus(
      fineLocation: result[0]! as bool,
      approximateOnly: result[1]! as bool,
      locationEnabled: result[2]! as bool,
      notifications: result[3]! as bool,
      bluetooth: result[4]! as bool,
      batteryUnrestricted: result[5]! as bool,
      gmsAvailable: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PermissionStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fineLocation, other.fineLocation) && _deepEquals(approximateOnly, other.approximateOnly) && _deepEquals(locationEnabled, other.locationEnabled) && _deepEquals(notifications, other.notifications) && _deepEquals(bluetooth, other.bluetooth) && _deepEquals(batteryUnrestricted, other.batteryUnrestricted) && _deepEquals(gmsAvailable, other.gmsAvailable);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class BleStatus {
  BleStatus({
    required this.connected,
    this.address,
    this.name,
    this.lastHr,
    required this.adapterOn,
  });

  bool connected;

  String? address;

  String? name;

  int? lastHr;

  bool adapterOn;

  List<Object?> _toList() {
    return <Object?>[
      connected,
      address,
      name,
      lastHr,
      adapterOn,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleStatus decode(Object result) {
    result as List<Object?>;
    return BleStatus(
      connected: result[0]! as bool,
      address: result[1] as String?,
      name: result[2] as String?,
      lastHr: result[3] as int?,
      adapterOn: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(connected, other.connected) && _deepEquals(address, other.address) && _deepEquals(name, other.name) && _deepEquals(lastHr, other.lastHr) && _deepEquals(adapterOn, other.adapterOn);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Result of the OS-kill diagnosis for a run (plan §3, W11).
class ExitDiagnosis {
  ExitDiagnosis({
    required this.runId,
    required this.reason,
    required this.timestampMs,
    this.description,
    required this.manufacturer,
  });

  String runId;

  ExitReason reason;

  /// Wall-clock epoch ms of the kill, 0 when none.
  int timestampMs;

  /// Raw `ApplicationExitInfo.description`, for the diagnostics screen.
  String? description;

  /// `Build.MANUFACTURER` lower-cased, so the UI picks per-OEM guidance.
  String manufacturer;

  List<Object?> _toList() {
    return <Object?>[
      runId,
      reason,
      timestampMs,
      description,
      manufacturer,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExitDiagnosis decode(Object result) {
    result as List<Object?>;
    return ExitDiagnosis(
      runId: result[0]! as String,
      reason: result[1]! as ExitReason,
      timestampMs: result[2]! as int,
      description: result[3] as String?,
      manufacturer: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExitDiagnosis || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(runId, other.runId) && _deepEquals(reason, other.reason) && _deepEquals(timestampMs, other.timestampMs) && _deepEquals(description, other.description) && _deepEquals(manufacturer, other.manufacturer);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class BleDevice {
  BleDevice({
    required this.address,
    this.name,
  });

  String address;

  String? name;

  List<Object?> _toList() {
    return <Object?>[
      address,
      name,
    ];
  }

  Object encode() {
    return _toList();  }

  static BleDevice decode(Object result) {
    result as List<Object?>;
    return BleDevice(
      address: result[0]! as String,
      name: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BleDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(address, other.address) && _deepEquals(name, other.name);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

sealed class RecorderEvent {
}

class TickEvent extends RecorderEvent {
  TickEvent({
    required this.elapsedMs,
    required this.lapElapsedMs,
    required this.lapDistanceM,
    this.lapPaceLiveSecPerKm,
    required this.totalDistanceM,
    this.hr,
    this.gpsAccuracyM,
    required this.state,
  });

  int elapsedMs;

  int lapElapsedMs;

  double lapDistanceM;

  /// Rolling 15 s "live" pace; differs from the verdict's trimmed pace.
  double? lapPaceLiveSecPerKm;

  double totalDistanceM;

  int? hr;

  double? gpsAccuracyM;

  RecorderState state;

  List<Object?> _toList() {
    return <Object?>[
      elapsedMs,
      lapElapsedMs,
      lapDistanceM,
      lapPaceLiveSecPerKm,
      totalDistanceM,
      hr,
      gpsAccuracyM,
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static TickEvent decode(Object result) {
    result as List<Object?>;
    return TickEvent(
      elapsedMs: result[0]! as int,
      lapElapsedMs: result[1]! as int,
      lapDistanceM: result[2]! as double,
      lapPaceLiveSecPerKm: result[3] as double?,
      totalDistanceM: result[4]! as double,
      hr: result[5] as int?,
      gpsAccuracyM: result[6] as double?,
      state: result[7]! as RecorderState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TickEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(elapsedMs, other.elapsedMs) && _deepEquals(lapElapsedMs, other.lapElapsedMs) && _deepEquals(lapDistanceM, other.lapDistanceM) && _deepEquals(lapPaceLiveSecPerKm, other.lapPaceLiveSecPerKm) && _deepEquals(totalDistanceM, other.totalDistanceM) && _deepEquals(hr, other.hr) && _deepEquals(gpsAccuracyM, other.gpsAccuracyM) && _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class LapEvent extends RecorderEvent {
  LapEvent({
    required this.index,
    required this.tMs,
    required this.distanceM,
    required this.source,
  });

  int index;

  int tMs;

  double distanceM;

  LapSource source;

  List<Object?> _toList() {
    return <Object?>[
      index,
      tMs,
      distanceM,
      source,
    ];
  }

  Object encode() {
    return _toList();  }

  static LapEvent decode(Object result) {
    result as List<Object?>;
    return LapEvent(
      index: result[0]! as int,
      tMs: result[1]! as int,
      distanceM: result[2]! as double,
      source: result[3]! as LapSource,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LapEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(index, other.index) && _deepEquals(tMs, other.tMs) && _deepEquals(distanceM, other.distanceM) && _deepEquals(source, other.source);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class CueEvent extends RecorderEvent {
  CueEvent({
    required this.kind,
  });

  CueKind kind;

  List<Object?> _toList() {
    return <Object?>[
      kind,
    ];
  }

  Object encode() {
    return _toList();  }

  static CueEvent decode(Object result) {
    result as List<Object?>;
    return CueEvent(
      kind: result[0]! as CueKind,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CueEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class FaultEvent extends RecorderEvent {
  FaultEvent({
    required this.kind,
    required this.message,
  });

  FaultKind kind;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static FaultEvent decode(Object result) {
    result as List<Object?>;
    return FaultEvent(
      kind: result[0]! as FaultKind,
      message: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FaultEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Recorder state transitions (start, pause, resume, stop, finalised), so a UI
/// that missed a tick still redraws; `status()` remains the source of truth.
class StateEvent extends RecorderEvent {
  StateEvent({
    required this.state,
    this.runId,
    required this.phase,
  });

  RecorderState state;

  String? runId;

  Phase phase;

  List<Object?> _toList() {
    return <Object?>[
      state,
      runId,
      phase,
    ];
  }

  Object encode() {
    return _toList();  }

  static StateEvent decode(Object result) {
    result as List<Object?>;
    return StateEvent(
      state: result[0]! as RecorderState,
      runId: result[1] as String?,
      phase: result[2]! as Phase,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) && _deepEquals(runId, other.runId) && _deepEquals(phase, other.phase);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Preset phase change (warmup -> work 1 -> recovery 1 -> ... -> cooldown).
class PhaseEvent extends RecorderEvent {
  PhaseEvent({
    required this.phase,
    required this.repIndex,
    required this.phaseDurationMs,
  });

  Phase phase;

  int repIndex;

  /// 0 for untimed phases (warmup, cooldown).
  int phaseDurationMs;

  List<Object?> _toList() {
    return <Object?>[
      phase,
      repIndex,
      phaseDurationMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static PhaseEvent decode(Object result) {
    result as List<Object?>;
    return PhaseEvent(
      phase: result[0]! as Phase,
      repIndex: result[1]! as int,
      phaseDurationMs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PhaseEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(phase, other.phase) && _deepEquals(repIndex, other.repIndex) && _deepEquals(phaseDurationMs, other.phaseDurationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RecordMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is Units) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is RecorderState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is Phase) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is LapSource) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is CueKind) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is FaultKind) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is StartError) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is PermissionKind) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is ExitReason) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is Preset) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is StartResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is RecorderStatus) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is OrphanJournal) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is ReplayConfig) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is PermissionStatus) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is BleStatus) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is ExitDiagnosis) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is BleDevice) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is TickEvent) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is LapEvent) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is CueEvent) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is FaultEvent) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is StateEvent) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    }    else if (value is PhaseEvent) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : RecordMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : Units.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : RecorderState.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : Phase.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : LapSource.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : CueKind.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : FaultKind.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : StartError.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : PermissionKind.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : ExitReason.values[value];
      case 139:
        return Preset.decode(readValue(buffer)!);
      case 140:
        return StartResult.decode(readValue(buffer)!);
      case 141:
        return RecorderStatus.decode(readValue(buffer)!);
      case 142:
        return OrphanJournal.decode(readValue(buffer)!);
      case 143:
        return ReplayConfig.decode(readValue(buffer)!);
      case 144:
        return PermissionStatus.decode(readValue(buffer)!);
      case 145:
        return BleStatus.decode(readValue(buffer)!);
      case 146:
        return ExitDiagnosis.decode(readValue(buffer)!);
      case 147:
        return BleDevice.decode(readValue(buffer)!);
      case 148:
        return TickEvent.decode(readValue(buffer)!);
      case 149:
        return LapEvent.decode(readValue(buffer)!);
      case 150:
        return CueEvent.decode(readValue(buffer)!);
      case 151:
        return FaultEvent.decode(readValue(buffer)!);
      case 152:
        return StateEvent.decode(readValue(buffer)!);
      case 153:
        return PhaseEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class RecorderApi {
  /// Constructor for [RecorderApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RecorderApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Idempotent: a second call while recording returns the running id. Must be
  /// called while the Activity is visible (the FGS is started from it, B2).
  Future<StartResult> start(RecordMode mode, Preset? preset, Units units) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode, preset, units]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as StartResult;
  }

  /// Debug builds only: like `start`, fed from a fixture instead of GPS/BLE.
  Future<StartResult> startReplay(RecordMode mode, Preset? preset, Units units, ReplayConfig replay) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.startReplay$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mode, preset, units, replay]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as StartResult;
  }

  /// Continue an orphaned journal after the user confirms (plan §3): writes the
  /// `gap` line, rebuilds the preset phase from the journal, restarts the FGS.
  /// Idempotent like `start`.
  Future<StartResult> resumeRecovered(String runId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.resumeRecovered$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[runId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as StartResult;
  }

  Future<void> pause() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> resume() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.resume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> lap(LapSource source) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.lap$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Finalises in Kotlin (journal -> tmp -> fsync -> rename -> delete journal). No-op when idle.
  Future<String?> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  Future<RecorderStatus> status() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as RecorderStatus;
  }

  /// Called on app open: journals without a finalised file, newest first. Never
  /// includes the run that is being recorded.
  Future<List<OrphanJournal>> recover() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.recover$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<OrphanJournal>();
  }

  /// Finalise an orphaned journal without resuming it. Returns the run file
  /// path relative to the app's files dir, or null when nothing was there.
  Future<String?> finalise(String runId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.finalise$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[runId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// Delete an unreadable orphan (`readable == false`). Never touches a run file.
  Future<void> discardJournal(String runId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.discardJournal$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[runId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setCues(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.setCues$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Run files on disk (`runs/` + `runs-archive/`) as `runId -> relative path`,
  /// for the Dart Reconciler. Journals and sidecars are not listed.
  Future<Map<String, String>> listRunFiles() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.listRunFiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as Map<Object?, Object?>).cast<String, String>();
  }

  /// Was the previous process killed by the OS while `runId` was recording?
  Future<ExitDiagnosis> exitDiagnosis(String runId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.RecorderApi.exitDiagnosis$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[runId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ExitDiagnosis;
  }
}

class PermissionsApi {
  /// Constructor for [PermissionsApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PermissionsApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<PermissionStatus> permissionStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.permissionStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PermissionStatus;
  }

  /// Shows the system prompt (or the enable-location dialog for `location` when
  /// the setting is off). Resolves when the user answers; true = granted.
  Future<bool> requestPermission(PermissionKind kind) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.requestPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[kind]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// The only Settings deep link allowed (plan §10): the app's battery page.
  Future<void> openBatterySettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.openBatterySettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openAppSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.PermissionsApi.openAppSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

class BleApi {
  /// Constructor for [BleApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BleApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Scan once for Heart Rate Profile (0x180D) devices to pair (≤ 10 s).
  Future<List<BleDevice>> bleScan() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.BleApi.bleScan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<BleDevice>();
  }

  /// Saves the address and connects; reconnects use autoConnect, never a rescan.
  Future<void> blePair(String address) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.BleApi.blePair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[address]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> bleForget() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.BleApi.bleForget$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<BleStatus> bleStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.run_solo.BleApi.bleStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as BleStatus;
  }
}

Stream<RecorderEvent> recorderEvents( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel recorderEventsChannel =
      EventChannel('dev.flutter.pigeon.run_solo.RecorderEvents.recorderEvents$instanceName', pigeonMethodCodec);
  return recorderEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as RecorderEvent;
  });
}
    
