// Regenerates lib/src/engine/zone_grid.dart: a coarse lat/lon grid of IANA
// zone ids, from package:timezone_finder's boundary polygons (a dev-only
// dependency, never shipped). Run from packages/run_engine:
//   dart run tool/gen_zone_grid.dart [cellDegrees]
import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:timezone/data/latest_10y.dart' as t10;
import 'package:timezone/data/latest_all.dart' as tall;
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone_finder/timezone_finder.dart' as finder;

Future<List<String?>> _rows(List<int> args) => Isolate.run(() {
  final (r0, r1, cols, cell) = (args[0], args[1], args[2], args[3] / 1000);
  tall.initializeTimeZones();
  final out = <String?>[];
  for (var r = r0; r < r1; r++) {
    final lat = 90 - (r + 0.5) * cell;
    for (var c = 0; c < cols; c++) {
      final lon = -180 + (c + 0.5) * cell;
      out.add(finder.findLocation(lon, lat)?.name);
    }
  }
  return out;
});

Future<void> main(List<String> argv) async {
  final cell = argv.isEmpty ? 0.25 : double.parse(argv.first);
  final cols = (360 / cell).round(), rows = (180 / cell).round();
  const workers = 6;
  final per = (rows / workers).ceil();
  final parts = await Future.wait([
    for (var w = 0; w < workers; w++)
      _rows([
        w * per,
        ((w + 1) * per).clamp(0, rows),
        cols,
        (cell * 1000).round(),
      ]),
  ]);
  final names = [for (final p in parts) ...p];

  // The shipped zone data is the 10-year database, which drops link ids:
  // map each used id onto a zone it has with the same offsets 2025-2034.
  t10.initializeTimeZones();
  final ten = tz.timeZoneDatabase.locations;
  final used = {...names.whereType<String>()}.toList()..sort();
  tall.initializeTimeZones();
  final full = tz.timeZoneDatabase.locations;
  List<int> sig(tz.Location l) => [
    for (var y = 2025; y < 2035; y++)
      for (var m = 1; m <= 12; m++)
        l
            .timeZone(DateTime.utc(y, m, 15).millisecondsSinceEpoch)
            .offset
            .inMinutes,
  ];
  final alias = <String, String>{};
  final tenSigs = {for (final e in ten.entries) e.key: sig(e.value)};
  for (final id in used) {
    if (ten.containsKey(id)) continue;
    final s = sig(full[id]!);
    final prefix = id.split('/').first;
    final match =
        tenSigs.entries
            .where((e) => e.value.toString() == s.toString())
            .map((e) => e.key)
            .toList()
          ..sort(
            (a, b) =>
                (b.startsWith(prefix) ? 1 : 0) - (a.startsWith(prefix) ? 1 : 0),
          );
    if (match.isEmpty) throw StateError('no 10y zone matches $id');
    alias[id] = match.first;
  }
  final ids = {for (final id in used) alias[id] ?? id}.toList()..sort();
  final index = {for (var i = 0; i < ids.length; i++) ids[i]: i + 1};

  // Row-major run-length encoding: (value, count) as varints.
  final bytes = <int>[];
  void varint(int v) {
    while (v >= 0x80) {
      bytes.add((v & 0x7f) | 0x80);
      v >>= 7;
    }
    bytes.add(v);
  }

  var i = 0;
  while (i < names.length) {
    final v = names[i] == null ? 0 : index[alias[names[i]] ?? names[i]]!;
    var j = i;
    while (j < names.length &&
        (names[j] == null ? 0 : index[alias[names[j]] ?? names[j]]!) == v) {
      j++;
    }
    varint(v);
    varint(j - i);
    i = j;
  }
  final packed = base64.encode(bytes);
  final b = StringBuffer()
    ..writeln('// GENERATED by tool/gen_zone_grid.dart; do not edit.')
    ..writeln(
      '// $cell-degree cells, ${ids.length} zones, ${bytes.length} B RLE.',
    )
    ..writeln('const double zoneGridCellDeg = $cell;')
    ..writeln('const List<String> zoneGridIds = [');
  for (final id in ids) {
    b.writeln("  '$id',");
  }
  b.writeln('];');
  b.writeln("const String zoneGridRle = '''");
  for (var k = 0; k < packed.length; k += 100) {
    b.writeln(packed.substring(k, (k + 100).clamp(0, packed.length)));
  }
  b.writeln("''';");
  File('lib/src/engine/zone_grid.dart').writeAsStringSync(b.toString());
  stdout.writeln(
    'cells ${names.length} rle ${bytes.length} b64 ${packed.length} ids ${ids.length} aliases ${alias.length}',
  );
}
