package app.runsolo.core.replay

import app.runsolo.core.journal.JournalLine
import app.runsolo.core.model.CueProfile
import app.runsolo.core.model.HrReading
import app.runsolo.core.model.LapSource
import app.runsolo.core.model.LocationFix
import app.runsolo.core.model.Phase
import app.runsolo.core.model.RecoveryStyle
import app.runsolo.core.model.RunMode
import app.runsolo.core.model.SessionSpec
import app.runsolo.core.model.Step
import app.runsolo.core.model.StepKind
import app.runsolo.core.model.TargetKind
import app.runsolo.core.record.RecorderCore
import app.runsolo.core.record.SampleTicker
import kotlin.math.cos

/**
 * One replay scenario per session kind (Phase 3 §3.9, I5): the same trace and presses go through
 * the JVM contract generator (`replay_<kind>.json`) and through the real service in the emulator
 * job, which checks its run file against that fixture.
 *
 * The trace is closed-loop: it is generated by driving a [RecorderCore] with it, second by
 * second, and the runner's speed for the next second follows the phase the core is in (work
 * pace in a rep, jog in a recovery), as a runner reacts to the cue. So distance steps end on the
 * trace's work pace instead of drifting against fixed time segments. The first fix is the start
 * position at t = 0; one fix and one HR reading per second after it, heading east.
 *
 * Specs equal the Dart `SessionCatalogue.expand(id, reps: n)` (reps cut to the catalogue
 * minimum to keep the emulator job short), plus fartlek, Cooper and parkrun.
 */
object ReplayScenarios {
    enum class Press { lap, startReps }

    /**
     * A press on the first fix whose trace time (ms since the trace's first fix) reaches [atMs],
     * one press per tick. Trace time, not elapsed: the service's clock starts a moment before
     * the first fix arrives, and the press must land on the same fix everywhere.
     */
    data class ScriptedPress(val atMs: Long, val press: Press)

    data class Scenario(
        val kind: String,
        val mode: RunMode,
        val spec: SessionSpec?,
        val fixes: List<LocationFix>,
        val hr: List<HrReading>,
        val presses: List<ScriptedPress>,
    )

    val KINDS = listOf("4x4", "400s", "30-30s", "yasso-800s", "1km-repeats", "fartlek", "cooper", "parkrun", "goal-10k", "goal-30min") // event-name-ok: debug replay ids, never in a store build

    private const val LAT0 = -33.8688
    private const val LON0 = 151.2093
    private const val ACCURACY_M = 5.0
    private const val WARMUP_S = 60
    private const val COOLDOWN_S = 60
    private const val WARMUP_MPS = 2.5
    private const val RECOVERY_MPS = 2.0

    fun create(kind: String): Scenario? = when (kind) {
        "4x4" -> structured(kind, SessionSpec.norwegian4x4(reps = 3), workMps = 4.2)
        "400s" -> structured(kind, distanceSpec("400s", "4 × 400 m", 4, 400, Step(StepKind.recovery, TargetKind.distance, 200, RecoveryStyle.jog, 1)), workMps = 4.0)
        "30-30s" -> structured(
            kind,
            SessionSpec.norwegian4x4(10, 30, 30).copy(templateId = "30-30s", name = "30/30s", hrBand = null, cueProfile = CueProfile.short),
            workMps = 4.5,
        )
        "yasso-800s" -> structured(kind, distanceSpec("yasso-800s", "Yasso 800s", 4, 800, Step(StepKind.recovery, TargetKind.equalToPreviousWork, 0, RecoveryStyle.jog, 1)), workMps = 4.0)
        "1km-repeats" -> structured(kind, distanceSpec("1km-repeats", "1 km repeats", 3, 1000, Step(StepKind.recovery, TargetKind.time, 120, RecoveryStyle.jog, 1)), workMps = 4.0)
        "parkrun" -> structured(kind, PARKRUN, workMps = 4.0, start = null) // event-name-ok: debug replay ids, never in a store build
        "cooper" -> structured(kind, SessionSpec.COOPER, workMps = 3.4, mode = RunMode.cooper, start = Press.startReps)
        "fartlek" -> fartlek()
        // GOAL runs (§G): one step from Start, then an open cool-down (60 s here, then the trace ends).
        "goal-10k" -> structured(kind, SessionSpec.goalDistance(10_000, "10K"), workMps = 4.0, start = null)
        "goal-30min" -> structured(kind, SessionSpec.goalTime(1_800, "30 minutes"), workMps = 3.5, start = null)
        else -> null
    }

    /**
     * parkrun (K1 reuses I2): no warm-up (founder 26-Sep: the 5000 m step begins at Start), and the
     * core stops the recording at 5.00 km. The name is neutral so the event's name is not in the
     * binary as copy (#49 review P3); the template id is a data key.
     */
    val PARKRUN = SessionSpec(
        templateId = "parkrun", templateVersion = 1, name = "5K time trial", // event-name-ok: a data key, never shown or spoken
        warmupSeconds = 0, cooldownSeconds = null, lapLockout = false, autoStop = true, cueProfile = CueProfile.standard, hrBand = null,
        steps = listOf(Step(StepKind.work, TargetKind.distance, 5_000, RecoveryStyle.run, 1)),
    )

    private fun distanceSpec(id: String, name: String, reps: Int, workM: Int, recovery: Step) = SessionSpec(
        templateId = id, templateVersion = 1, name = name,
        warmupSeconds = null, cooldownSeconds = null, lapLockout = false, cueProfile = CueProfile.standard, hrBand = null,
        steps = (1..reps).flatMap { r ->
            listOfNotNull(Step(StepKind.work, TargetKind.distance, workM, RecoveryStyle.run, r), if (r < reps) recovery.copy(rep = r) else null)
        },
    )

    /**
     * Warm-up jog, the press that starts rep 1 (a LAP; START REPS for Cooper), the steps at
     * [workMps] / recovery jog as the core moves through them, then a cool-down jog. Ends
     * [COOLDOWN_S] into the cool-down, or 3 s after the core asked to auto-stop.
     */
    private fun structured(kind: String, spec: SessionSpec, workMps: Double, mode: RunMode = RunMode.intervals, start: Press? = Press.lap): Scenario {
        val presses = listOfNotNull(start?.let { ScriptedPress(WARMUP_S * 1000L, it) })
        val (fixes, hr) = closedLoop(mode, spec, presses, workMps)
        return Scenario(kind, mode, spec, fixes, hr, presses)
    }

    /** A Laps run with the fartlek session: fixed surges, a LAP at the start and end of each. */
    private fun fartlek(): Scenario {
        val segments = listOf(120 to 2.8, 30 to 4.5, 150 to 2.8, 45 to 4.6, 135 to 2.8)
        val fixes = TraceFixture.straightLine(segments, LAT0, LON0, ACCURACY_M, startT = 0)
        val hr = (1..fixes.size - 1).map { i -> HrReading(i * 1000L - 300, if (fixes[i].speedMps!! > 4.0) 168 else 148) }
        val presses = listOf(120, 150, 300, 345).map { ScriptedPress(it * 1000L, Press.lap) }
        return Scenario("fartlek", RunMode.laps, SessionSpec.FARTLEK, fixes, hr, presses)
    }

    private fun closedLoop(mode: RunMode, spec: SessionSpec, presses: List<ScriptedPress>, workMps: Double): Pair<List<LocationFix>, List<HrReading>> {
        val core = RecorderCore(mode, spec)
        val ticker = SampleTicker(wall = { 0L })
        val driver = Driver(core, ticker, presses)
        val mPerDegLon = 111_320.0 * cos(Math.toRadians(LAT0))
        val fixes = ArrayList<LocationFix>()
        val hr = ArrayList<HrReading>()
        core.start(0)
        fixes.add(LocationFix(0, LAT0, LON0, 10.0, ACCURACY_M, 0.0))
        driver.step(fixes[0], null)
        var eastM = 0.0
        var cooldownLeft = COOLDOWN_S
        var stopIn = -1
        var i = 0
        while (true) {
            i++
            check(i < 4 * 3600) { "replay scenario for ${spec.templateId} never finished" }
            val phase = core.phase
            val mps = when (phase) {
                Phase.work -> workMps
                Phase.recovery -> RECOVERY_MPS
                Phase.warmup, Phase.cooldown, Phase.none -> WARMUP_MPS
            }
            eastM += mps
            val t = i * 1000L
            val fix = LocationFix(t, LAT0, LON0 + eastM / mPerDegLon, 10.0, ACCURACY_M, mps)
            val reading = HrReading(t - 300, when (phase) {
                Phase.work -> 165 + i % 5
                Phase.recovery -> 145
                else -> 130
            })
            fixes.add(fix)
            hr.add(reading)
            val out = driver.step(fix, reading)
            if (stopIn < 0 && out.any { it is RecorderCore.Output.AutoStop }) stopIn = 3
            if (stopIn >= 0 && stopIn-- == 0) break
            if (core.phase == Phase.cooldown && --cooldownLeft == 0) break
        }
        return fixes to hr
    }

    /**
     * One delivered fix, exactly as `RecordingSession` in replay mode: HR and the fix reach the
     * ticker, a due scripted press is pressed (a notification LAP or START REPS), then this
     * second's sample and the core tick. [onSamples] / [onOutputs] let a caller journal them.
     */
    class Driver(
        val core: RecorderCore,
        val ticker: SampleTicker,
        private val presses: List<ScriptedPress>,
        private val onSamples: (List<JournalLine.Sample>) -> Unit = {},
        private val onOutputs: (List<RecorderCore.Output>) -> Unit = {},
    ) {
        private var pressed = 0
        private var firstT: Long? = null

        fun step(fix: LocationFix, reading: HrReading?): List<RecorderCore.Output> {
            val t = fix.t
            val traceT = t - (firstT ?: t.also { firstT = it })
            reading?.let { ticker.onHr(it) }
            ticker.onFix(fix)
            if (pressed < presses.size && traceT >= presses[pressed].atMs) {
                val p = presses[pressed++]
                onOutputs(
                    when (p.press) {
                        Press.lap -> core.lap(LapSource.notification, t).second
                        Press.startReps -> core.startReps(t).second
                    },
                )
            }
            val samples = ticker.tick(t)
            onSamples(samples)
            val out = core.tick(t, ticker.distanceM, !ticker.gpsLost(t))
            onOutputs(out)
            return out
        }
    }
}
