package app.runsolo.core.replay

import app.runsolo.core.journal.JournalLine
import app.runsolo.core.model.CueProfile
import app.runsolo.core.model.HrReading
import app.runsolo.core.model.FastStartRule
import app.runsolo.core.model.HrDriftRule
import app.runsolo.core.model.LapSource
import app.runsolo.core.model.LiveBoard
import app.runsolo.core.model.LiveBoardKind
import app.runsolo.core.model.LiveContext
import app.runsolo.core.model.LiveEntry
import app.runsolo.core.model.LiveTarget
import app.runsolo.core.model.LocationFix
import app.runsolo.core.model.NudgePlan
import app.runsolo.core.model.RepFadeRule
import app.runsolo.core.model.Phase
import app.runsolo.core.model.RecoveryStyle
import app.runsolo.core.model.RunMode
import app.runsolo.core.model.SessionSpec
import app.runsolo.core.model.Step
import app.runsolo.core.model.StepKind
import app.runsolo.core.model.TargetKind
import app.runsolo.core.record.RecorderCore
import app.runsolo.core.record.SampleTicker
import kotlin.math.cos
import kotlin.math.floor

/**
 * One replay scenario per session kind (Phase 3 §3.9, I5): the same trace and presses go through
 * the JVM contract generator (`replay_<kind>.json`) and through the real service in the emulator
 * job, which checks its run file against that fixture.
 *
 * The trace is closed-loop: it is generated by driving a [RecorderCore] with it, second by
 * second, and the runner's speed for the next second follows the phase the core is in (work
 * pace in a rep, jog in a recovery), as a runner reacts to the cue. So distance steps end on the
 * trace's work pace instead of drifting against fixed time segments. The first fix is the start
 * position at t = 0; one fix and one HR reading per second after it, heading east.
 *
 * Specs equal the Dart `SessionCatalogue.expand(id, reps: n)` (reps cut to the catalogue
 * minimum to keep the emulator job short), plus fartlek, Cooper and parkrun.
 *
 * The `t4-*` kinds (Phase 4 §5 T4) carry a [LiveContext] as the app would pack it at Start, so
 * the live compares and nudges run: the JVM transcript fixture pins what is said and when, and
 * the emulator job checks the service says the same.
 */
object ReplayScenarios {
    enum class Press { lap, startReps, pause }

    /**
     * A press on the first fix whose trace time (ms since the trace's first fix) reaches [atMs],
     * one press per tick. Trace time, not elapsed: the service's clock starts a moment before
     * the first fix arrives, and the press must land on the same fix everywhere.
     */
    data class ScriptedPress(val atMs: Long, val press: Press)

    data class Scenario(
        val kind: String,
        val mode: RunMode,
        val spec: SessionSpec?,
        val fixes: List<LocationFix>,
        val hr: List<HrReading>,
        val presses: List<ScriptedPress>,
        /** T4: the live compare's history for this replay (null: a silent run, as I5). */
        val context: LiveContext? = null,
    )

    /** Phase 4 T4: replays with a LiveContext, each with a transcript fixture (declared first: [KINDS] reads it). */
    val T4_KINDS = listOf("t4-free-5k-fast", "t4-free-10k-fade", "t4-400s-fade", "t4-cooper-fast", "t4-5k-target")

    val KINDS = listOf("4x4", "400s", "30-30s", "yasso-800s", "1km-repeats", "fartlek", "cooper", "parkrun", "goal-10k", "goal-30min", "pause-end") + T4_KINDS // event-name-ok: debug replay ids, never in a store build

    private const val LAT0 = -33.8688
    private const val LON0 = 151.2093
    private const val ACCURACY_M = 5.0
    private const val WARMUP_S = 60
    private const val COOLDOWN_S = 60
    private const val WARMUP_MPS = 2.5
    private const val RECOVERY_MPS = 2.0

    fun create(kind: String): Scenario? = when (kind) {
        "4x4" -> structured(kind, SessionSpec.norwegian4x4(reps = 3), workMps = 4.2)
        "400s" -> structured(kind, distanceSpec("400s", "4 × 400 m", 4, 400, Step(StepKind.recovery, TargetKind.distance, 200, RecoveryStyle.jog, 1)), workMps = 4.0)
        "30-30s" -> structured(
            kind,
            SessionSpec.norwegian4x4(10, 30, 30).copy(templateId = "30-30s", name = "30/30s", hrBand = null, cueProfile = CueProfile.short),
            workMps = 4.5,
        )
        "yasso-800s" -> structured(kind, distanceSpec("yasso-800s", "Yasso 800s", 4, 800, Step(StepKind.recovery, TargetKind.equalToPreviousWork, 0, RecoveryStyle.jog, 1)), workMps = 4.0)
        "1km-repeats" -> structured(kind, distanceSpec("1km-repeats", "1 km repeats", 3, 1000, Step(StepKind.recovery, TargetKind.time, 120, RecoveryStyle.jog, 1)), workMps = 4.0)
        "parkrun" -> structured(kind, PARKRUN, workMps = 4.0, start = null) // event-name-ok: debug replay ids, never in a store build
        "cooper" -> structured(kind, SessionSpec.COOPER, workMps = 3.4, mode = RunMode.cooper, start = Press.startReps)
        "fartlek" -> fartlek()
        // #88: a Free run paused at 4:00 (the finish screen's tap) that never resumes; the trace
        // runs on a minute, the replay's end stops it while paused, so the file ends at the pause.
        "pause-end" -> pauseEnd()
        // GOAL runs (§G): one step from Start, then an open cool-down (60 s here, then the trace ends).
        "goal-10k" -> structured(kind, SessionSpec.goalDistance(10_000, "10K"), workMps = 4.0, start = null)
        "goal-30min" -> structured(kind, SessionSpec.goalTime(1_800, "30 min"), workMps = 3.5, start = null)
        // T4: Free 5K out too fast (km 1 at 3:47/km), then 5:08/km; the 5K board and a fast-start rule.
        "t4-free-5k-fast" -> free(kind, 5_050.0, T4.free5k, hr = { _ -> 152 }) { d -> if (d < 1_000) 4.4 else 3.25 }
        // T4: Free 10K fading from 4:38/km to 5:39/km, HR climbing 2 a km; the 5K and 10K boards and HR drift.
        "t4-free-10k-fade" -> free(kind, 10_050.0, T4.free10k, hr = { d -> T4.fadeHr(d) }) { d -> T4.fadeMps(d) }
        // T4: 8 x 400 m, each rep 0.08 m/s slower than the last; the 8 x 400 board and the rep-fade rule.
        "t4-400s-fade" -> structured(
            kind, distanceSpec("400s", "8 × 400 m", 8, 400, Step(StepKind.recovery, TargetKind.distance, 200, RecoveryStyle.jog, 1)),
            workMps = 0.0, context = T4.eightBy400, work = { rep, _ -> 4.3 - 0.08 * (rep - 1) },
        )
        // T4: a Cooper out hard (3.9 m/s for 3 min) that settles at 3.2 m/s; three past tests.
        "t4-cooper-fast" -> structured(
            kind, SessionSpec.COOPER, workMps = 0.0, mode = RunMode.cooper, start = Press.startReps, context = T4.cooper,
            work = { _, s -> if (s < 180) 3.9 else 3.2 },
        )
        // T4: the timed 5 km against a predicted 23:00 (4:36/km even), km 1 fast, then a touch slow.
        "t4-5k-target" -> structured(kind, PARKRUN, workMps = 0.0, start = null, context = T4.target5k, work = { _, s -> if (s < 220) 4.5 else 3.55 })
        else -> null
    }

    /**
     * T4 contexts, as the engine packs them at Start (plan §3.2 / §3.5): boards of three runs, the
     * CR1 nudge rules with the engine's own lines (`CoachingRules` in `coaching_rules.dart`).
     */
    object T4 {
        const val FAST_START_5K = "Easy start. Your best 5K went out slower than this."
        const val REP_FADE = "That one dropped off a bit. Hold your form on the next."
        const val HR_DRIFT = "Heart rate's up for this pace today. Fine to ease a touch."
        private const val DAY = 86_400_000L

        /** Even-paced entries: one per pace (s/km), [km] whole-km splits from Start. */
        private fun distanceBoard(key: String, label: String, km: Int, paces: List<Int>) = LiveBoard(
            key = key, label = label, kind = LiveBoardKind.distance, targetM = km * 1_000.0,
            entries = paces.mapIndexed { i, p ->
                LiveEntry("t4-$key-$i", (i + 1) * DAY, fromStartSplitsMs = (1..km).map { k -> k * p * 1_000L }, finalMetric = km * p * 1_000.0)
            },
        )

        val free5k = LiveContext(
            boards = listOf(distanceBoard("be:5000", "5K", 5, listOf(288, 294, 300))),
            nudges = NudgePlan(version = 1, fastStart = FastStartRule(km1MaxMs = 276_480, text = FAST_START_5K)),
            builtAtMs = 0, engineVersion = 3,
        )

        fun fadeMps(d: Double): Double = 3.6 - 0.065 * floor(d / 1_000)
        fun fadeHr(d: Double): Int = 148 + 2 * floor(d / 1_000).toInt()

        /** Three recent runs per km at the live pace (within 2%), their HR 7 to 9 under the live km's. */
        val free10k = LiveContext(
            boards = listOf(distanceBoard("be:5000", "5K", 5, listOf(285, 292, 300)), distanceBoard("be:10000", "10K", 10, listOf(290, 300, 310))),
            nudges = NudgePlan(
                version = 1,
                hrDrift = HrDriftRule(
                    kmSamples = (0 until 10).map { k ->
                        val pace = 1_000 / fadeMps(k * 1_000.0)
                        val hr = fadeHr(k * 1_000.0).toDouble()
                        listOf(pace to hr - 8, pace * 1.02 to hr - 9, pace * 0.98 to hr - 7)
                    },
                    text = HR_DRIFT,
                ),
            ),
            builtAtMs = 0, engineVersion = 3,
        )

        val eightBy400 = LiveContext(
            boards = listOf(
                LiveBoard(
                    key = "d400x8", label = "8 × 400 m", kind = LiveBoardKind.intervals,
                    entries = listOf(240.0, 245.0, 250.0).mapIndexed { i, p ->
                        LiveEntry("t4-d400x8-$i", (i + 1) * DAY, liveRepPacesSecPerKm = List(8) { p }, finalMetric = p)
                    },
                ),
            ),
            nudges = NudgePlan(version = 1, repFade = RepFadeRule(listOf(null, null, 8.0, 8.0, 10.0, 10.0, 12.0, 12.0), REP_FADE)),
            builtAtMs = 0, engineVersion = 3,
        )

        val cooper = LiveContext(boards = emptyList(), cooperHistory = listOf(44.0, 46.5, 47.2), builtAtMs = 0, engineVersion = 3)

        val target5k = LiveContext(boards = emptyList(), target = LiveTarget(distanceM = 5_000.0, targetMs = 1_380_000, predicted = true), builtAtMs = 0, engineVersion = 3)
    }

    /**
     * parkrun (K1 reuses I2): no warm-up (founder 26-Sep: the 5000 m step begins at Start), and the
     * core stops the recording at 5.00 km. The name is neutral so the event's name is not in the
     * binary as copy (#49 review P3); the template id is a data key.
     */
    val PARKRUN = SessionSpec(
        templateId = "parkrun", templateVersion = 1, name = "5K time trial", // event-name-ok: a data key, never shown or spoken
        warmupSeconds = 0, cooldownSeconds = null, lapLockout = false, autoStop = true, cueProfile = CueProfile.standard, hrBand = null,
        steps = listOf(Step(StepKind.work, TargetKind.distance, 5_000, RecoveryStyle.run, 1)),
    )

    private fun distanceSpec(id: String, name: String, reps: Int, workM: Int, recovery: Step) = SessionSpec(
        templateId = id, templateVersion = 1, name = name,
        warmupSeconds = null, cooldownSeconds = null, lapLockout = false, cueProfile = CueProfile.standard, hrBand = null,
        steps = (1..reps).flatMap { r ->
            listOfNotNull(Step(StepKind.work, TargetKind.distance, workM, RecoveryStyle.run, r), if (r < reps) recovery.copy(rep = r) else null)
        },
    )

    /**
     * Warm-up jog, the press that starts rep 1 (a LAP; START REPS for Cooper), the steps at
     * [workMps] / recovery jog as the core moves through them, then a cool-down jog. Ends
     * [COOLDOWN_S] into the cool-down, or 3 s after the core asked to auto-stop.
     */
    private fun structured(
        kind: String,
        spec: SessionSpec,
        workMps: Double,
        mode: RunMode = RunMode.intervals,
        start: Press? = Press.lap,
        context: LiveContext? = null,
        /** Work pace by (rep, seconds into the work step); [workMps] throughout by default. */
        work: (rep: Int, workS: Int) -> Double = { _, _ -> workMps },
    ): Scenario {
        val presses = listOfNotNull(start?.let { ScriptedPress(WARMUP_S * 1000L, it) })
        val (fixes, hr) = closedLoop(mode, spec, presses, work)
        return Scenario(kind, mode, spec, fixes, hr, presses, context)
    }

    /** T4: a Free run at [mps] by distance so far, one fix and one HR reading a second, to [endM]. */
    private fun free(kind: String, endM: Double, context: LiveContext, hr: (Double) -> Int, mps: (Double) -> Double): Scenario {
        val mPerDegLon = 111_320.0 * cos(Math.toRadians(LAT0))
        val fixes = arrayListOf(LocationFix(0, LAT0, LON0, 10.0, ACCURACY_M, 0.0))
        val readings = ArrayList<HrReading>()
        var eastM = 0.0
        var i = 0
        while (eastM < endM) {
            i++
            val v = mps(eastM)
            readings.add(HrReading(i * 1000L - 300, hr(eastM)))
            eastM += v
            fixes.add(LocationFix(i * 1000L, LAT0, LON0 + eastM / mPerDegLon, 10.0, ACCURACY_M, v))
        }
        return Scenario(kind, RunMode.free, null, fixes, readings, emptyList(), context)
    }

    /** A Laps run with the fartlek session: fixed surges, a LAP at the start and end of each. */
    private fun fartlek(): Scenario {
        val segments = listOf(120 to 2.8, 30 to 4.5, 150 to 2.8, 45 to 4.6, 135 to 2.8)
        val fixes = TraceFixture.straightLine(segments, LAT0, LON0, ACCURACY_M, startT = 0)
        val hr = (1..fixes.size - 1).map { i -> HrReading(i * 1000L - 300, if (fixes[i].speedMps!! > 4.0) 168 else 148) }
        val presses = listOf(120, 150, 300, 345).map { ScriptedPress(it * 1000L, Press.lap) }
        return Scenario("fartlek", RunMode.laps, SessionSpec.FARTLEK, fixes, hr, presses)
    }

    private fun pauseEnd(): Scenario {
        val fixes = TraceFixture.straightLine(listOf(300 to 3.0), LAT0, LON0, ACCURACY_M, startT = 0)
        val hr = (1 until fixes.size).map { i -> HrReading(i * 1000L - 300, 150) }
        return Scenario("pause-end", RunMode.free, null, fixes, hr, listOf(ScriptedPress(240_000, Press.pause)))
    }

    private fun closedLoop(mode: RunMode, spec: SessionSpec, presses: List<ScriptedPress>, work: (Int, Int) -> Double): Pair<List<LocationFix>, List<HrReading>> {
        val core = RecorderCore(mode, spec)
        val ticker = SampleTicker(wall = { 0L })
        val driver = Driver(core, ticker, presses)
        val mPerDegLon = 111_320.0 * cos(Math.toRadians(LAT0))
        val fixes = ArrayList<LocationFix>()
        val hr = ArrayList<HrReading>()
        core.start(0)
        fixes.add(LocationFix(0, LAT0, LON0, 10.0, ACCURACY_M, 0.0))
        driver.step(fixes[0], null)
        var eastM = 0.0
        var cooldownLeft = COOLDOWN_S
        var stopIn = -1
        var workS = 0
        var i = 0
        while (true) {
            i++
            check(i < 4 * 3600) { "replay scenario for ${spec.templateId} never finished" }
            val phase = core.phase
            if (phase != Phase.work) workS = 0
            val mps = when (phase) {
                Phase.work -> work(core.repIndex, workS++)
                Phase.recovery -> RECOVERY_MPS
                Phase.warmup, Phase.cooldown, Phase.none -> WARMUP_MPS
            }
            eastM += mps
            val t = i * 1000L
            val fix = LocationFix(t, LAT0, LON0 + eastM / mPerDegLon, 10.0, ACCURACY_M, mps)
            val reading = HrReading(t - 300, when (phase) {
                Phase.work -> 165 + i % 5
                Phase.recovery -> 145
                else -> 130
            })
            fixes.add(fix)
            hr.add(reading)
            val out = driver.step(fix, reading)
            if (stopIn < 0 && out.any { it is RecorderCore.Output.AutoStop }) stopIn = 3
            if (stopIn >= 0 && stopIn-- == 0) break
            if (core.phase == Phase.cooldown && --cooldownLeft == 0) break
        }
        return fixes to hr
    }

    /**
     * One delivered fix, exactly as `RecordingSession` in replay mode: HR and the fix reach the
     * ticker, a due scripted press is pressed (a notification LAP or START REPS), then this
     * second's sample and the core tick. [onSamples] / [onOutputs] let a caller journal them.
     */
    class Driver(
        val core: RecorderCore,
        val ticker: SampleTicker,
        private val presses: List<ScriptedPress>,
        private val onSamples: (List<JournalLine.Sample>) -> Unit = {},
        private val onOutputs: (List<RecorderCore.Output>) -> Unit = {},
        /** A scripted pause at this time (the caller journals it). */
        private val onPause: (Long) -> Unit = {},
    ) {
        private var pressed = 0
        private var firstT: Long? = null

        fun step(fix: LocationFix, reading: HrReading?): List<RecorderCore.Output> {
            val t = fix.t
            val traceT = t - (firstT ?: t.also { firstT = it })
            reading?.let { ticker.onHr(it) }
            ticker.onFix(fix)
            if (pressed < presses.size && traceT >= presses[pressed].atMs) {
                val p = presses[pressed++]
                onOutputs(
                    when (p.press) {
                        Press.lap -> core.lap(LapSource.notification, t).second
                        Press.startReps -> core.startReps(t).second
                        Press.pause -> {
                            // As RecordingSession.pause: the core and the ticker stop measuring.
                            core.pause(t)
                            ticker.onPause()
                            onPause(t)
                            emptyList()
                        }
                    },
                )
            }
            val samples = ticker.tick(t)
            onSamples(samples)
            val out = core.tick(t, ticker.distanceM, !ticker.gpsLost(t))
            onOutputs(out)
            return out
        }
    }
}
