import 'dart:convert';
import 'dart:typed_data';

import 'package:timezone/data/latest_10y.dart' as tzdata;
import 'package:timezone/timezone.dart' as tz;

import '../model/run_file.dart';
import 'run_identity.dart';
import 'zone_grid.dart';

/// The wall-clock zone a run started in: an IANA id when one is known, and
/// the UTC offset in minutes at the run's start instant (DST-correct).
typedef RunLocalZone = ({String? zoneId, int offsetMin});

/// Works out WHERE a run started so its time of day is the clock there, not
/// the phone's current zone. Offline: the start fix goes through a coarse
/// zone grid (0.1 degree cells, about 11 km, [zoneGridRle]; generated by
/// tool/gen_zone_grid.dart), the zone's rules give the offset at that instant
/// (package:timezone, 10-year database: DST is exact for 2025 to 2034 and
/// standard time outside it). Within one cell of a zone border the grid can
/// name the neighbouring zone; that only matters where the two differ.
abstract final class RunZone {
  static bool _ready = false;

  static void _init() {
    if (_ready) return;
    tzdata.initializeTimeZones();
    _ready = true;
  }

  static Int32List? _starts;
  static Uint16List? _values;

  static void _decodeGrid() {
    final bytes = base64.decode(zoneGridRle.replaceAll('\n', ''));
    final starts = <int>[];
    final values = <int>[];
    var at = 0, cell = 0;
    int varint() {
      var v = 0, shift = 0;
      while (true) {
        final b = bytes[at++];
        v |= (b & 0x7f) << shift;
        if (b < 0x80) return v;
        shift += 7;
      }
    }

    while (at < bytes.length) {
      final v = varint();
      final n = varint();
      starts.add(cell);
      values.add(v);
      cell += n;
    }
    _starts = Int32List.fromList(starts);
    _values = Uint16List.fromList(values);
  }

  static int _cell(int row, int col) {
    final starts = _starts!;
    var lo = 0, hi = starts.length - 1;
    final index = row * (360 / zoneGridCellDeg).round() + col;
    while (lo < hi) {
      final mid = (lo + hi + 1) >> 1;
      if (starts[mid] <= index) {
        lo = mid;
      } else {
        hi = mid - 1;
      }
    }
    return _values![lo];
  }

  /// The IANA zone covering ([lat], [lon]); null at sea (a coastal start
  /// takes the nearest land cell within two cells) or on any failure. Never
  /// throws.
  static String? zoneAt(double lat, double lon) {
    try {
      if (lat.isNaN || lon.isNaN || lat.abs() > 90 || lon.abs() > 180) {
        return null;
      }
      if (_starts == null) _decodeGrid();
      final n = (180 / zoneGridCellDeg).round();
      final m = (360 / zoneGridCellDeg).round();
      final r0 = ((90 - lat) / zoneGridCellDeg).floor().clamp(0, n - 1);
      final c0 = ((lon + 180) / zoneGridCellDeg).floor().clamp(0, m - 1);
      for (var d = 0; d <= 2; d++) {
        // Ring d around the cell, nearest ring first.
        for (var dr = -d; dr <= d; dr++) {
          for (var dc = -d; dc <= d; dc++) {
            if (d > 0 && dr.abs() != d && dc.abs() != d) continue;
            final r = r0 + dr;
            if (r < 0 || r >= n) continue;
            final v = _cell(r, (c0 + dc) % m);
            if (v != 0) return zoneGridIds[v - 1];
          }
        }
      }
      return null;
    } catch (_) {
      return null;
    }
  }

  /// [zoneId]'s UTC offset in minutes at [instant]; null for an id the zone
  /// database does not know. Never throws.
  static int? offsetAt(String zoneId, DateTime instant) {
    try {
      _init();
      final zone = tz
          .getLocation(zoneId)
          .timeZone(instant.toUtc().millisecondsSinceEpoch);
      return zone.offset.inMinutes;
    } catch (_) {
      return null;
    }
  }

  /// The zone [run] started in, best evidence first:
  /// 1. [zoneId], already worked out and stored in the sidecar;
  /// 2. the run file's `tz`: the phone's IANA zone when the run began, which
  ///    phones keep current as the runner travels (not for an import, whose
  ///    `tz` is a placeholder, and a bare "UTC" is no evidence);
  /// 3. [stampedOffsetMin], the phone's offset stamped at finish;
  /// 4. the start fix, through the coarse zone grid (imports, and files
  ///    with no usable zone).
  /// Null when none is available: the caller then falls back to the phone's
  /// current zone, which is only right for a run that has no better record.
  static RunLocalZone? resolve(
    RunFile run, {
    String? zoneId,
    int? stampedOffsetMin,
  }) {
    RunLocalZone? from(String? id) {
      if (id == null) return null;
      final m = offsetAt(id, run.start);
      return m == null ? null : (zoneId: id, offsetMin: m);
    }

    final stored = from(zoneId);
    if (stored != null) return stored;
    final utcLike = const {'UTC', 'Etc/UTC', 'GMT', 'Etc/GMT'}.contains(run.tz);
    if (!run.app.startsWith('import:') && !utcLike) {
      final fromFile = from(run.tz);
      if (fromFile != null) return fromFile;
    }
    if (stampedOffsetMin != null) {
      return (zoneId: null, offsetMin: stampedOffsetMin);
    }
    final fix = RunIdentity.startOf(run);
    return fix == null ? null : from(zoneAt(fix.lat, fix.lon));
  }
}
