// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.runsolo.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PlatformApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Mode picked at Start. Mirrors `RunMode` in `package:run_engine`. */
enum class RecordMode(val raw: Int) {
  FOUR_BY_FOUR(0),
  FREE(1);

  companion object {
    fun ofRaw(raw: Int): RecordMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class Units(val raw: Int) {
  KM(0),
  MI(1);

  companion object {
    fun ofRaw(raw: Int): Units? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RecorderState(val raw: Int) {
  IDLE(0),
  RECORDING(1),
  PAUSED(2),
  FINALISING(3);

  companion object {
    fun ofRaw(raw: Int): RecorderState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Phase of a preset (4x4) run; `none` in free mode or outside a rep. */
enum class Phase(val raw: Int) {
  NONE(0),
  WARMUP(1),
  WORK(2),
  RECOVERY(3),
  COOLDOWN(4);

  companion object {
    fun ofRaw(raw: Int): Phase? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LapSource(val raw: Int) {
  BUTTON(0),
  NOTIFICATION(1),
  VOLUME_KEY(2),
  AUTO(3);

  companion object {
    fun ofRaw(raw: Int): LapSource? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CueKind(val raw: Int) {
  HALFWAY(0),
  THIRTY_SECONDS(1),
  PHASE_END(2),
  START(3),
  STOP(4);

  companion object {
    fun ofRaw(raw: Int): CueKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class FaultKind(val raw: Int) {
  GPS_LOST(0),
  GPS_WEAK(1),
  HR_DISCONNECTED(2),
  JOURNAL_WRITE_FAILED(3),
  LOW_STORAGE(4);

  companion object {
    fun ofRaw(raw: Int): FaultKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Typed errors returned by `start` (plan §2). Never a stringly-typed map. */
enum class StartError(val raw: Int) {
  NO_FINE_PERMISSION(0),
  APPROXIMATE_ONLY(1),
  LOCATION_OFF(2),
  LOW_STORAGE(3),
  NOTIFICATIONS_DENIED(4),
  ALREADY_RUNNING(5);

  companion object {
    fun ofRaw(raw: Int): StartError? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The 4x4 preset written into the file header; drives cues and the detector.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Preset (
  val reps: Long,
  val workSeconds: Long,
  val recoverySeconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Preset {
      val reps = pigeonVar_list[0] as Long
      val workSeconds = pigeonVar_list[1] as Long
      val recoverySeconds = pigeonVar_list[2] as Long
      return Preset(reps, workSeconds, recoverySeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reps,
      workSeconds,
      recoverySeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Preset
    return PlatformApiPigeonUtils.deepEquals(this.reps, other.reps) && PlatformApiPigeonUtils.deepEquals(this.workSeconds, other.workSeconds) && PlatformApiPigeonUtils.deepEquals(this.recoverySeconds, other.recoverySeconds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.reps)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.workSeconds)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.recoverySeconds)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StartResult (
  val runId: String? = null,
  val error: StartError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartResult {
      val runId = pigeonVar_list[0] as String?
      val error = pigeonVar_list[1] as StartError?
      return StartResult(runId, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      runId,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StartResult
    return PlatformApiPigeonUtils.deepEquals(this.runId, other.runId) && PlatformApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.runId)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.error)
    return result
  }
}

/**
 * Enough for a recreated UI to redraw mid-run.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RecorderStatus (
  val state: RecorderState,
  val runId: String? = null,
  val elapsedMs: Long,
  val lapIndex: Long,
  val gpsFix: Boolean,
  val hrConnected: Boolean,
  val phase: Phase,
  val repIndex: Long,
  val phaseRemainingMs: Long,
  val preset: Preset? = null,
  val journalOk: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecorderStatus {
      val state = pigeonVar_list[0] as RecorderState
      val runId = pigeonVar_list[1] as String?
      val elapsedMs = pigeonVar_list[2] as Long
      val lapIndex = pigeonVar_list[3] as Long
      val gpsFix = pigeonVar_list[4] as Boolean
      val hrConnected = pigeonVar_list[5] as Boolean
      val phase = pigeonVar_list[6] as Phase
      val repIndex = pigeonVar_list[7] as Long
      val phaseRemainingMs = pigeonVar_list[8] as Long
      val preset = pigeonVar_list[9] as Preset?
      val journalOk = pigeonVar_list[10] as Boolean
      return RecorderStatus(state, runId, elapsedMs, lapIndex, gpsFix, hrConnected, phase, repIndex, phaseRemainingMs, preset, journalOk)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      runId,
      elapsedMs,
      lapIndex,
      gpsFix,
      hrConnected,
      phase,
      repIndex,
      phaseRemainingMs,
      preset,
      journalOk,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RecorderStatus
    return PlatformApiPigeonUtils.deepEquals(this.state, other.state) && PlatformApiPigeonUtils.deepEquals(this.runId, other.runId) && PlatformApiPigeonUtils.deepEquals(this.elapsedMs, other.elapsedMs) && PlatformApiPigeonUtils.deepEquals(this.lapIndex, other.lapIndex) && PlatformApiPigeonUtils.deepEquals(this.gpsFix, other.gpsFix) && PlatformApiPigeonUtils.deepEquals(this.hrConnected, other.hrConnected) && PlatformApiPigeonUtils.deepEquals(this.phase, other.phase) && PlatformApiPigeonUtils.deepEquals(this.repIndex, other.repIndex) && PlatformApiPigeonUtils.deepEquals(this.phaseRemainingMs, other.phaseRemainingMs) && PlatformApiPigeonUtils.deepEquals(this.preset, other.preset) && PlatformApiPigeonUtils.deepEquals(this.journalOk, other.journalOk)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.state)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.runId)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.elapsedMs)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.lapIndex)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.gpsFix)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.hrConnected)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.phase)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.repIndex)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.phaseRemainingMs)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.preset)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.journalOk)
    return result
  }
}

/**
 * An in-progress journal found on app open without a finalised run file.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OrphanJournal (
  val runId: String,
  val lastLineAgeMs: Long,
  val mode: RecordMode
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OrphanJournal {
      val runId = pigeonVar_list[0] as String
      val lastLineAgeMs = pigeonVar_list[1] as Long
      val mode = pigeonVar_list[2] as RecordMode
      return OrphanJournal(runId, lastLineAgeMs, mode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      runId,
      lastLineAgeMs,
      mode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OrphanJournal
    return PlatformApiPigeonUtils.deepEquals(this.runId, other.runId) && PlatformApiPigeonUtils.deepEquals(this.lastLineAgeMs, other.lastLineAgeMs) && PlatformApiPigeonUtils.deepEquals(this.mode, other.mode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.runId)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.lastLineAgeMs)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.mode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleDevice (
  val address: String,
  val name: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleDevice {
      val address = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String?
      return BleDevice(address, name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      address,
      name,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleDevice
    return PlatformApiPigeonUtils.deepEquals(this.address, other.address) && PlatformApiPigeonUtils.deepEquals(this.name, other.name)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.address)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.name)
    return result
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class RecorderEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class TickEvent (
  val elapsedMs: Long,
  val lapElapsedMs: Long,
  val lapDistanceM: Double,
  /** Rolling 15 s "live" pace; differs from the verdict's trimmed pace. */
  val lapPaceLiveSecPerKm: Double? = null,
  val totalDistanceM: Double,
  val hr: Long? = null,
  val gpsAccuracyM: Double? = null,
  val state: RecorderState
) : RecorderEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TickEvent {
      val elapsedMs = pigeonVar_list[0] as Long
      val lapElapsedMs = pigeonVar_list[1] as Long
      val lapDistanceM = pigeonVar_list[2] as Double
      val lapPaceLiveSecPerKm = pigeonVar_list[3] as Double?
      val totalDistanceM = pigeonVar_list[4] as Double
      val hr = pigeonVar_list[5] as Long?
      val gpsAccuracyM = pigeonVar_list[6] as Double?
      val state = pigeonVar_list[7] as RecorderState
      return TickEvent(elapsedMs, lapElapsedMs, lapDistanceM, lapPaceLiveSecPerKm, totalDistanceM, hr, gpsAccuracyM, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      elapsedMs,
      lapElapsedMs,
      lapDistanceM,
      lapPaceLiveSecPerKm,
      totalDistanceM,
      hr,
      gpsAccuracyM,
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TickEvent
    return PlatformApiPigeonUtils.deepEquals(this.elapsedMs, other.elapsedMs) && PlatformApiPigeonUtils.deepEquals(this.lapElapsedMs, other.lapElapsedMs) && PlatformApiPigeonUtils.deepEquals(this.lapDistanceM, other.lapDistanceM) && PlatformApiPigeonUtils.deepEquals(this.lapPaceLiveSecPerKm, other.lapPaceLiveSecPerKm) && PlatformApiPigeonUtils.deepEquals(this.totalDistanceM, other.totalDistanceM) && PlatformApiPigeonUtils.deepEquals(this.hr, other.hr) && PlatformApiPigeonUtils.deepEquals(this.gpsAccuracyM, other.gpsAccuracyM) && PlatformApiPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.elapsedMs)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.lapElapsedMs)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.lapDistanceM)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.lapPaceLiveSecPerKm)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.totalDistanceM)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.hr)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.gpsAccuracyM)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.state)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LapEvent (
  val index: Long,
  val tMs: Long,
  val distanceM: Double,
  val source: LapSource
) : RecorderEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LapEvent {
      val index = pigeonVar_list[0] as Long
      val tMs = pigeonVar_list[1] as Long
      val distanceM = pigeonVar_list[2] as Double
      val source = pigeonVar_list[3] as LapSource
      return LapEvent(index, tMs, distanceM, source)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      tMs,
      distanceM,
      source,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LapEvent
    return PlatformApiPigeonUtils.deepEquals(this.index, other.index) && PlatformApiPigeonUtils.deepEquals(this.tMs, other.tMs) && PlatformApiPigeonUtils.deepEquals(this.distanceM, other.distanceM) && PlatformApiPigeonUtils.deepEquals(this.source, other.source)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.index)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.tMs)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.distanceM)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.source)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CueEvent (
  val kind: CueKind
) : RecorderEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CueEvent {
      val kind = pigeonVar_list[0] as CueKind
      return CueEvent(kind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CueEvent
    return PlatformApiPigeonUtils.deepEquals(this.kind, other.kind)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.kind)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FaultEvent (
  val kind: FaultKind,
  val message: String
) : RecorderEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FaultEvent {
      val kind = pigeonVar_list[0] as FaultKind
      val message = pigeonVar_list[1] as String
      return FaultEvent(kind, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FaultEvent
    return PlatformApiPigeonUtils.deepEquals(this.kind, other.kind) && PlatformApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.message)
    return result
  }
}
private open class PlatformApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RecordMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Units.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RecorderState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          Phase.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LapSource.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CueKind.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FaultKind.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          StartError.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Preset.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartResult.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecorderStatus.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OrphanJournal.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleDevice.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TickEvent.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LapEvent.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CueEvent.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FaultEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RecordMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is Units -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is RecorderState -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is Phase -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is LapSource -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is CueKind -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is FaultKind -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is StartError -> {
        stream.write(136)
        writeValue(stream, value.raw.toLong())
      }
      is Preset -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is StartResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is RecorderStatus -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is OrphanJournal -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is BleDevice -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is TickEvent -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is LapEvent -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is CueEvent -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is FaultEvent -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val PlatformApiPigeonMethodCodec = StandardMethodCodec(PlatformApiPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RecorderApi {
  /** Idempotent: a second call while recording returns the running id. */
  fun start(mode: RecordMode, preset: Preset?, units: Units): StartResult
  fun pause()
  fun resume()
  fun lap(source: LapSource)
  /** Finalises in Kotlin (journal -> tmp -> fsync -> rename -> delete journal). No-op when idle. */
  fun stop(): String?
  fun status(): RecorderStatus
  /** Called on app open: journals without a finalised file. */
  fun recover(): List<OrphanJournal>
  /** Finalise an orphaned journal without resuming it. */
  fun finalise(runId: String)
  fun setCues(enabled: Boolean)

  companion object {
    /** The codec used by RecorderApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `RecorderApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RecorderApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as RecordMode
            val presetArg = args[1] as Preset?
            val unitsArg = args[2] as Units
            val wrapped: List<Any?> = try {
              listOf(api.start(modeArg, presetArg, unitsArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.resume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resume()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.lap$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as LapSource
            val wrapped: List<Any?> = try {
              api.lap(sourceArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.stop())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.status())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.recover$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.recover())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.finalise$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val runIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.finalise(runIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.RecorderApi.setCues$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setCues(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BleApi {
  /** Scan once for Heart Rate Profile (0x180D) devices to pair. */
  fun bleScan(callback: (Result<List<BleDevice>>) -> Unit)
  fun blePair(address: String)
  fun bleForget()

  companion object {
    /** The codec used by BleApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `BleApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BleApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.BleApi.bleScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.bleScan{ result: Result<List<BleDevice>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PlatformApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PlatformApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.BleApi.blePair$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.blePair(addressArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.run_solo.BleApi.bleForget$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.bleForget()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class PlatformApiPigeonStreamHandler<T>(
    val wrapper: PlatformApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface PlatformApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class RecorderEventsStreamHandler : PlatformApiPigeonEventChannelWrapper<RecorderEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: RecorderEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.run_solo.RecorderEvents.recorderEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PlatformApiPigeonStreamHandler<RecorderEvent>(streamHandler)
      EventChannel(messenger, channelName, PlatformApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from PlatformApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<RecorderEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
